fn main() {
    // Expose the build target triple to the crate so tests can locate the
    // fetched ffmpeg sidecar at `binaries/<name>-<triple>` (the suffix
    // scripts/fetch-ffmpeg.mjs uses). Cargo sets `TARGET` for build scripts.
    println!(
        "cargo:rustc-env=SUNDAYREC_TARGET_TRIPLE={}",
        std::env::var("TARGET").unwrap_or_default()
    );

    // Link AVFoundation on macOS so the camera/mic authorization query
    // (`media::permissions`) can resolve `AVCaptureDevice` at runtime. Without it
    // the class lookup returns `None` and we degrade to "Unknown" (proceed) — this
    // is what makes the TCC pre-check actually functional. `CARGO_CFG_TARGET_OS`
    // reflects the BUILD TARGET (unlike `cfg!`, which would read the host).
    if std::env::var("CARGO_CFG_TARGET_OS").as_deref() == Ok("macos") {
        println!("cargo:rustc-link-lib=framework=AVFoundation");
    }

    // The `updater:default` permission may only exist when the updater plugin
    // is actually registered — a static reference in capabilities/default.json
    // broke every `--no-default-features` build ("Permission updater:default
    // not found"). Build scripts see enabled features as CARGO_FEATURE_* env
    // vars, so the capability is GENERATED here iff the feature is on (and
    // removed when off, so a feature-off rebuild after a feature-on one works).
    let cap = std::path::Path::new("capabilities/updater.generated.json");
    if std::env::var_os("CARGO_FEATURE_UPDATER").is_some() {
        std::fs::write(
            cap,
            concat!(
                "{\n",
                "  \"$schema\": \"../gen/schemas/desktop-schema.json\",\n",
                "  \"identifier\": \"updater\",\n",
                "  \"description\": \"Generated by build.rs when the updater feature is enabled\",\n",
                "  \"windows\": [\"main\"],\n",
                "  \"permissions\": [\"updater:default\"]\n",
                "}\n"
            ),
        )
        .expect("writing generated updater capability");
    } else {
        let _ = std::fs::remove_file(cap);
    }

    // The vendored VAD model must be byte-identical to the one the code was
    // written against. A swapped or truncated ONNX graph does NOT crash a VAD —
    // it returns confident, wrong probabilities — so the check happens at the
    // earliest moment there is: before the bytes are ever linked in. Only under
    // `--features vad` (build scripts see enabled features as CARGO_FEATURE_*),
    // so a default build pays nothing.
    if std::env::var_os("CARGO_FEATURE_VAD").is_some() {
        use sha2::{Digest, Sha256};
        // Duplicated from `sundayrec_core::vad::{VAD_MODEL_FILE_NAME,
        // VAD_MODEL_SHA256}` because a build script cannot depend on a workspace
        // member. `build_script_pins_the_same_digest_as_the_core` in
        // src/vad/mod.rs reads these two literals back out of this file and
        // fails if they ever drift from the core constants.
        const MODEL: &str = "resources/vad/silero_vad_op18_ifless.onnx";
        const SHA256: &str = "7671cd04b004e9076da0d4a7b1a5aec36adf161c39230c1cb94a4fd5db6bbd28";
        println!("cargo:rerun-if-changed={MODEL}");
        let bytes = std::fs::read(MODEL)
            .unwrap_or_else(|e| panic!("--features vad needs the vendored model at {MODEL}: {e}"));
        let hex: String = Sha256::digest(&bytes)
            .iter()
            .map(|b| format!("{b:02x}"))
            .collect();
        assert_eq!(
            hex, SHA256,
            "{MODEL} does not match the pinned SHA-256 — the checkout is corrupt or the model \
             was swapped. Re-fetch it from the URL in sundayrec_core::vad::VAD_MODEL_SOURCE_URL."
        );
    }

    tauri_build::build()
}
