fn main() {
    // Expose the build target triple to the crate so tests can locate the
    // fetched ffmpeg sidecar at `binaries/<name>-<triple>` (the suffix
    // scripts/fetch-ffmpeg.mjs uses). Cargo sets `TARGET` for build scripts.
    println!(
        "cargo:rustc-env=SUNDAYREC_TARGET_TRIPLE={}",
        std::env::var("TARGET").unwrap_or_default()
    );

    // Link AVFoundation on macOS so the camera/mic authorization query
    // (`media::permissions`) can resolve `AVCaptureDevice` at runtime. Without it
    // the class lookup returns `None` and we degrade to "Unknown" (proceed) — this
    // is what makes the TCC pre-check actually functional. `CARGO_CFG_TARGET_OS`
    // reflects the BUILD TARGET (unlike `cfg!`, which would read the host).
    if std::env::var("CARGO_CFG_TARGET_OS").as_deref() == Ok("macos") {
        println!("cargo:rustc-link-lib=framework=AVFoundation");
    }

    // The `updater:default` permission may only exist when the updater plugin
    // is actually registered — a static reference in capabilities/default.json
    // broke every `--no-default-features` build ("Permission updater:default
    // not found"). Build scripts see enabled features as CARGO_FEATURE_* env
    // vars, so the capability is GENERATED here iff the feature is on (and
    // removed when off, so a feature-off rebuild after a feature-on one works).
    let cap = std::path::Path::new("capabilities/updater.generated.json");
    if std::env::var_os("CARGO_FEATURE_UPDATER").is_some() {
        std::fs::write(
            cap,
            concat!(
                "{\n",
                "  \"$schema\": \"../gen/schemas/desktop-schema.json\",\n",
                "  \"identifier\": \"updater\",\n",
                "  \"description\": \"Generated by build.rs when the updater feature is enabled\",\n",
                "  \"windows\": [\"main\"],\n",
                "  \"permissions\": [\"updater:default\"]\n",
                "}\n"
            ),
        )
        .expect("writing generated updater capability");
    } else {
        let _ = std::fs::remove_file(cap);
    }

    tauri_build::build()
}
