//! The e-mail relay's client half: an outbox, a pump and one local record.
//!
//! A volunteer who wants an e-mail when a recording fails should not have to
//! type an SMTP host, a user name and an app password into a settings panel.
//! With the relay they type an address and click a link in the confirmation
//! mail. This app renders every message itself and POSTs it to the SundaySuite
//! endpoint, which sends it and stores no content.
//!
//! The pure decisions — which row may leave, when a row is too old, which rows
//! go when the queue is full — are `sundayrec_core::relay`. This module is
//! everything that has a side effect:
//!
//!   - [`config`] — where the endpoint is, and the key to write to it;
//!   - [`store`] — the sqlite tables from migration 0006, plus the local
//!     subscription record and the "already said it" ledger;
//!   - [`wire`] — the request bodies, and the three doors that put one in the
//!     outbox (A3's dispatcher uses the same doors the buttons do);
//!   - [`sender`] — the socket, the classification of what came back, and the
//!     supervised pump loop.
//!
//! ## The one record everything is gated on
//!
//! [`RelaySubscription`] lives in the `app_setting` bag under
//! [`KEY_SUBSCRIPTION`], as one JSON blob — the shape `telemetry::ConsentRecord`
//! uses, and for the same reason: it is a single small fact about this machine
//! with no rows to join, and putting it in the bag keeps it out of `Settings`
//! (which crosses IPC as a whole and is version-pinned by a test).
//!
//! ⚠️ **Its existence, not its state, is what opens the pump's gate.** See
//! [`RelaySubscription::gate`] and [`store::subscription_clear`] — the record
//! has to outlive the `unsubscribe` row it queued.

use serde::{Deserialize, Serialize};
use ts_rs::TS;

use sundayrec_core::relay::RelayGate;

pub mod config;
pub mod sender;
pub mod store;
pub mod wire;

/// The `app_setting` key holding the [`RelaySubscription`] JSON. ABSENT means
/// this machine has never enrolled an address — which is not "unsubscribed",
/// it is "the relay does not exist here", and the pump does not run at all.
pub const KEY_SUBSCRIPTION: &str = "notify.relay";

/// Where a subscription is in the double opt-in.
///
/// Three states and no fourth: "unsubscribed" is the ABSENCE of a record, not a
/// state within one. A fourth value meaning "gone" would be a record the pump's
/// gate still counts as enrolled, i.e. a machine that keeps a dead subscription
/// alive forever.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, TS)]
#[ts(export, export_to = "RelaySubscriptionState.ts")]
#[serde(rename_all = "lowercase")]
pub enum RelaySubscriptionState {
    /// The address was enrolled and the confirmation mail requested. Nothing
    /// else may be sent to it.
    Pending,
    /// The link was clicked. Alerts may go out.
    Confirmed,
    /// The endpoint answered `410 recipient_suppressed` / `not_allowed`: the
    /// address bounces or complained. Nothing but an unsubscribe reaches it
    /// again — and the panel SAYS so, because the alternative is a volunteer who
    /// believes they are covered and hears nothing when a service fails.
    Suppressed,
}

/// What this machine knows about its own subscription.
///
/// Local only. The endpoint holds the authoritative copy (and is polled while
/// this one says `Pending` — a link clicked on a phone is invisible here until
/// somebody asks).
///
/// ## Why the unsubscribe token is stored and the confirm token is not
///
/// Both are minted here, 32 random bytes each, and only their SHA-256 is ever
/// sent — a dump of the endpoint's database cannot confirm a subscription or
/// unsubscribe anybody. The CONFIRM token is then forgotten: its one use is the
/// link inside the mail that was just handed over, and "send it again" mints a
/// new one on purpose ([`crate::commands::notify_relay::relay_resend`]), so a
/// stored copy would be a credential kept for nothing.
///
/// The UNSUBSCRIBE token has to survive, because every later mail carries the
/// footer link built from it (RFC 8058, and the endpoint's `List-Unsubscribe`
/// header points at the same URL). Losing it would leave a subscriber whose only
/// way out is this app's own button — which is exactly the situation the footer
/// exists to prevent.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct RelaySubscription {
    /// UUID v7, minted on this machine when the address was enrolled. Wholly
    /// independent of the telemetry install id: the two are generated by
    /// different code at different moments and are never sent together, so
    /// nothing links an address to the anonymous pseudonym.
    pub sub_id: String,
    /// The address as it was enrolled, normalised. Stored in the clear because
    /// the panel shows it back and the endpoint must be told where to send.
    pub address: String,
    pub state: RelaySubscriptionState,
    /// Unix ms the address was enrolled.
    pub enrolled_at: i64,
    /// Unix ms the endpoint reported the link had been clicked.
    pub confirmed_at: Option<i64>,
    /// Unix ms of the last status poll. Absent means never polled.
    pub last_checked: Option<i64>,
    /// The raw unsubscribe token — see the struct docs. Never leaves this
    /// machine except inside the mail footer it builds.
    pub unsub_token: String,
}

impl RelaySubscription {
    /// The pump's gate, read off this record.
    ///
    /// ⚠️ `enrolled` is `true` for EVERY state, suppressed and mid-unsubscribe
    /// included. That is not sloppiness, it is the contract
    /// `sundayrec_core::relay::RelayGate` documents: the row that carries "stop
    /// sending me mail" is gated on this record, so a record cleared the moment
    /// the user clicked would strand that row behind a shut gate and the
    /// endpoint would go on sending. The record is cleared when the row LEAVES
    /// the queue — see [`store::subscription_clear`] and the pump.
    pub fn gate(&self) -> RelayGate {
        RelayGate {
            enrolled: true,
            confirmed: self.state == RelaySubscriptionState::Confirmed,
            suppressed: self.state == RelaySubscriptionState::Suppressed,
        }
    }
}

/// The gate for a machine with no record at all: nothing is enrolled, so the
/// pump is `Blocked` before it reads the queue or resolves a hostname.
pub fn gate_of(subscription: Option<&RelaySubscription>) -> RelayGate {
    subscription
        .map(RelaySubscription::gate)
        .unwrap_or_default()
}

#[cfg(test)]
mod tests {
    use super::*;

    fn sub(state: RelaySubscriptionState) -> RelaySubscription {
        RelaySubscription {
            sub_id: "018f3a2b-7c4d-7e1f-9a2b-3c4d5e6f7a8b".into(),
            address: "frivillig@kirka.no".into(),
            state,
            enrolled_at: 1_000,
            confirmed_at: None,
            last_checked: None,
            unsub_token: "a".repeat(64),
        }
    }

    #[test]
    fn every_state_is_enrolled_including_the_suppressed_one() {
        // THE trap, as a property: whatever the state, a record that exists
        // opens the gate — so an unsubscribe row can always leave.
        for state in [
            RelaySubscriptionState::Pending,
            RelaySubscriptionState::Confirmed,
            RelaySubscriptionState::Suppressed,
        ] {
            assert!(
                sub(state).gate().enrolled,
                "{state:?} must count as enrolled, or its unsubscribe strands"
            );
        }
        assert!(!gate_of(None).enrolled);
    }

    #[test]
    fn only_a_confirmed_unsuppressed_record_lets_a_notification_out() {
        let g = sub(RelaySubscriptionState::Confirmed).gate();
        assert!(g.confirmed && !g.suppressed);
        for state in [
            RelaySubscriptionState::Pending,
            RelaySubscriptionState::Suppressed,
        ] {
            assert!(
                !sub(state).gate().confirmed || sub(state).gate().suppressed,
                "{state:?} must not pass a send row"
            );
        }
        assert!(sub(RelaySubscriptionState::Suppressed).gate().suppressed);
    }

    #[test]
    fn the_state_words_match_the_column_they_are_stored_as() {
        for (state, word) in [
            (RelaySubscriptionState::Pending, "pending"),
            (RelaySubscriptionState::Confirmed, "confirmed"),
            (RelaySubscriptionState::Suppressed, "suppressed"),
        ] {
            assert_eq!(
                serde_json::to_string(&state).expect("serialise"),
                format!("\"{word}\"")
            );
        }
    }

    #[test]
    fn the_record_round_trips_through_the_settings_bag() {
        let s = sub(RelaySubscriptionState::Confirmed);
        let json = serde_json::to_string(&s).expect("serialise");
        assert!(json.contains("\"subId\""), "camelCase on the wire: {json}");
        assert_eq!(
            serde_json::from_str::<RelaySubscription>(&json).expect("round-trip"),
            s
        );
    }
}
