// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One live camera-preview frame emitted to the renderer over
 * [`RECORDING_FRAME_EVENT`] while recording video. `data` is a base64-encoded
 * JPEG (drop it straight into `src="data:image/jpeg;base64,…"`); it comes from
 * the RECORDING ffmpeg's second MJPEG-to-stdout output, so it needs no second
 * camera process (macOS gives the camera a single owner). Mirrors the preview's
 * `PreviewFrame` shape (base64 payload + monotonic seq), trimmed to what the
 * recording tile needs.
 */
export type RecordingFrame = { 
/**
 * Base64-encoded JPEG bytes (no data-URL prefix).
 */
data: string, 
/**
 * Monotonic frame counter since this segment's preview started (1-based).
 */
seq: number, };
