// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Options for [`RecorderEngine::start`].
 */
export type RecordingOpts = { 
/**
 * Stored microphone/mixer name to fuzzy-match against the enumerated audio
 * devices. Empty → first/default device.
 */
audio_device_name: string, 
/**
 * Stored camera name to match against video devices. `None` → audio-only.
 */
video_device_name: string | null, 
/**
 * Absolute output file path the (first) segment is written to.
 */
output_path: string, 
/**
 * User opted into stop-on-silence.
 */
stop_on_silence: boolean, 
/**
 * Silence threshold in dB (clamped by the core filter builder).
 */
silence_threshold_db: number | null, 
/**
 * Minutes of continuous silence before stop-on-silence fires (1–120).
 */
silence_timeout_minutes: number, 
/**
 * Capture framerate.
 */
framerate: number, 
/**
 * `true` → stereo, `false` → mono.
 */
stereo: boolean, 
/**
 * Rotate to a fresh segment every N minutes (0 = off).
 */
split_minutes: number, 
/**
 * Auto-stop the whole session after N minutes (0 = off).
 */
manual_max_minutes: number, };
