// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A classified recorder error sent to the renderer.
 */
export type RecordingEvent = { 
/**
 * Stable error code the UI localises (snake_case, e.g. `device_disconnected`,
 * or `stuck_recording` for the watchdog).
 */
code: string, 
/**
 * Human-readable detail for logs / a diagnostics surface.
 */
message: string, };
