// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AudioBackendKind } from "./AudioBackendKind";

/**
 * One ASIO device with the capabilities the picker needs. `id` and `name` are
 * the same string today (ASIO addresses devices by name); `id` is kept separate
 * so a later backend can use a stabler handle without changing the contract.
 */
export type AsioDevice = { 
/**
 * Stable-ish identifier the recorder addresses (the ASIO device name).
 */
id: string, 
/**
 * Human-readable device name as reported by the driver.
 */
name: string, 
/**
 * Always [`AudioBackendKind::Asio`] — present so the device shares one shape
 * with any future unified device list.
 */
backend: AudioBackendKind, 
/**
 * Number of input channels the interface exposes under this one device.
 */
inputChannels: number, 
/**
 * Number of output channels (for later playback work; 0 if none).
 */
outputChannels: number, 
/**
 * The device's default/native sample rate (Hz), or 0 if unknown.
 */
defaultSampleRate: number, 
/**
 * Standard sample rates (Hz) the device supports.
 */
supportedSampleRates: Array<number>, };
