// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One addressable input channel. `label` is human-readable. cpal reports channel
 * *count*, not per-channel driver names, so v1 labels are `"Input N"`; true
 * driver-supplied names would need the ASIO SDK's `ASIOGetChannelInfo` (TODO).
 */
export type AudioChannel = { 
/**
 * 0-based channel index as the recorder addresses it.
 */
index: number, 
/**
 * Human-readable label, e.g. `"Input 1"`.
 */
label: string, };
