// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which OS audio backend a device is reached through. The frontend renders this
 * as a small badge next to the device name ("ASIO" / "WASAPI" / "CoreAudio") so
 * the user can see they're getting the low-latency multichannel path — the rest
 * of the picker UI is identical across backends.
 */
export type AudioBackendKind = "asio" | "wasapi" | "coreaudio";
