// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WarnSeverity } from "./WarnSeverity";

/**
 * A non-fatal observation the backend wants on screen NOW.
 *
 * The renderer localises on [`Self::code`] (a `notify.*` key) and interpolates
 * [`Self::params`]; [`Self::msg`] is the backend's own wording, used verbatim
 * when the code is unknown to this renderer build. That ordering matters: a
 * backend that learns a new warning before the renderer does still says
 * something true instead of nothing.
 */
export type BackendWarning = { 
/**
 * Stable snake_case code — see [`code`].
 */
code: string, 
/**
 * Human-readable fallback (Norwegian), or `None` to rely on the code alone.
 */
msg: string | null, 
/**
 * Toast severity.
 */
severity: WarnSeverity, 
/**
 * Interpolation values for the localized string (`{file}`, `{device}`, …).
 */
params: { [key in string]: string }, };
