// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One channel's measured max peak over the scan window.
 */
export type ChannelPeak = { 
/**
 * 1-based channel number as astats reports it (channel 1 = input 1).
 */
channel: number, 
/**
 * Max peak (dBFS) seen during the scan; −120 = effectively silent.
 */
peakDb: number, };
