// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The chapter marker as the renderer's `.meta.json` sidecar stores it — the
 * wire twin of [`Chapter`] (`time` in whole seconds from the start of the main
 * content). Exported for the renderer's `RecordingMetadata.chapters`; the
 * Rust export path reads the sidecar as opaque JSON and never deserialises
 * this directly.
 */
export type ChapterMarker = { time: number, title: string, };
