// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a dialog command hands the webview: the token, and the name to show.
 */
export type ChosenPlace = { 
/**
 * Opaque, random, session-scoped. Hand it back; never parse it.
 */
token: string, 
/**
 * The place's last component — what the page shows («Skrivebord»).
 */
displayName: string, };
