// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Per-cloud-service backup preferences (enable/auto-upload/target folder).
 * Tokens are NOT here — they belong to the OS keychain when the cloud glue
 * lands; this is only the panel's configuration state. Mirrors the Electron
 * `CloudServiceSettings`.
 */
export type CloudServicePrefs = { enabled: boolean, autoUpload: boolean, folderId: string | null, folderName: string | null, folderPath: string | null, };
