// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What became of one suggestion.
 *
 * `Rejected` has no producer today — the panel has a "use it" button per kind
 * and no dismiss gesture, so a suggestion nobody uses is `LeftAlone`. It is in
 * the vocabulary because a redesigned panel that grows an explicit dismiss must
 * not need a schema bump, and because the two are genuinely different: one is a
 * decision, the other is silence.
 */
export type CompanionSuggestionOutcome = "accepted" | "rejected" | "left_alone";
