// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CompanionKind } from "./CompanionKind";
import type { CompanionOutcome } from "./CompanionOutcome";

/**
 * One companion outcome and how many times it happened, as it goes on the wire.
 *
 * Two closed enums and a count. There is no field here for the suggested text,
 * the rewrite, a transcript, a recording name or a timestamp — see the module
 * docs.
 */
export type CompanionOutcomeReport = { kind: CompanionKind, outcome: CompanionOutcome, count: number, };
