// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CompanionSuggestionKind } from "./CompanionSuggestionKind";
import type { CompanionSuggestionOutcome } from "./CompanionSuggestionOutcome";

/**
 * One companion suggestion's fate, as stored.
 *
 * Categories and outcomes only. The suggested title, the summary, the chapter
 * titles, the user's rewrite and the transcript they were derived from are all
 * absent by SHAPE — there is no field on this type any of them could occupy,
 * which is the same guarantee the renderer's event type makes and the reason
 * neither of them carries a free-text field "for debugging".
 */
export type CompanionSuggestionRecord = { kind: CompanionSuggestionKind, outcome: CompanionSuggestionOutcome, 
/**
 * Only ever `true` alongside [`CompanionSuggestionOutcome::Accepted`]: the
 * user took the suggestion as a starting point and rewrote it, which is the
 * more interesting of the two accepted cases.
 */
editedAfterAccept: boolean, 
/**
 * The app version that produced the suggestion. Without it an outcome
 * cannot be attributed to the companion that earned it, and a corpus that
 * cannot separate versions cannot tell whether a change to the companion
 * helped.
 */
appVersion: string, };
