// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which of the companion's suggestions an outcome is about.
 *
 * A separate type from [`CompanionSuggestionKind`] even though the two agree
 * today, and deliberately so: the local vocabulary belongs to the panel and may
 * grow (its doc comment already contemplates `highlights`), while this one
 * belongs to a sentence a user agreed to and to an endpoint that 4xxs anything
 * outside it. [`Self::from_record`] is the seam, and it is an exhaustive match
 * so that widening the local set fails to compile instead of failing in the
 * field.
 */
export type CompanionKind = "title" | "description" | "chapters";
