// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One chapter marker as surfaced to the renderer. `time` in seconds. Mirrors
 * the renderer-facing shape (camelCase) rather than reusing the internal
 * `editor::Chapter` (which isn't a TS-exported type). Built from the
 * deterministic detectors via [`to_companion_chapter`].
 */
export type CompanionChapter = { time: number, title: string, };
