// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What became of one suggestion.
 *
 * Four members where the stored record has three plus a boolean. The record
 * keeps `edited_after_accept` beside the outcome and normalises it away for the
 * two outcomes it cannot mean anything for; here that normalisation is part of
 * the vocabulary, so "left alone, then rewritten" is not merely unused but
 * unrepresentable, and nothing downstream needs to know the rule.
 *
 * The distinction between [`Self::Accepted`] and [`Self::AcceptedEdited`] is
 * the one the privacy text draws in words — *beholdt slik det ble foreslått*
 * versus *skrevet om etterpå* — and it is also the one worth having: a
 * suggestion that is a useful starting point and a suggestion that is a usable
 * answer are two different verdicts on the companion.
 */
export type CompanionOutcome = "accepted" | "accepted_edited" | "rejected" | "left_alone";
