// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which of the companion's suggestions an outcome is about. A closed
 * vocabulary, mirroring the renderer's `CompanionSuggestionKind`
 * (`legacy/renderer/pages/editor/companion-feedback.ts`) — `highlights` is
 * absent from both for the same reason: the panel only lets you SEEK to a
 * highlight, so there is no accept/reject decision to observe.
 */
export type CompanionSuggestionKind = "title" | "description" | "chapters";
