// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which of the app's guesses a person corrected.
 *
 * The two families answer different questions and must not be merged. A
 * `sermon_pick_*` correction says the detector promoted the WRONG BLOCK — it
 * mistook a reading or a song for the sermon. A `sermon_start` / `sermon_end`
 * correction says the block was right and the boundaries were not. Averaging
 * them together would produce a number that describes neither failure.
 */
export type CorrectionSignal = "sermon_start" | "sermon_end" | "sermon_pick_start" | "sermon_pick_end";
