// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How far it moved, as a coarse band over the ABSOLUTE distance.
 *
 * The variants are named for their wire strings rather than for the numbers, so
 * that reading a match arm and reading a stored row agree. See
 * [`CORRECTION_BAND_EDGES_SEC`] for the boundaries and the module docs for why
 * they are these.
 */
export type CorrectionBand = "under_15s" | "15_30s" | "30_60s" | "60_120s" | "over_120s";
