// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CorrectionBand } from "./CorrectionBand";
import type { CorrectionDirection } from "./CorrectionDirection";
import type { CorrectionSignal } from "./CorrectionSignal";

/**
 * One banded correction and how many times it happened, as it goes on the wire.
 *
 * Three closed enums and a count. There is no field here for a duration, a
 * timestamp, a name or a path — see the module docs.
 */
export type CorrectionReport = { signal: CorrectionSignal, direction: CorrectionDirection, band: CorrectionBand, count: number, };
