// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which way along the recording the boundary moved.
 *
 * The sign convention is [`crate::trim_feedback`]'s, and it is stated as words
 * rather than carried as a sign bit precisely because inverting it is
 * invisible: the counts stay plausible, the tests stay green, and the tuning
 * stage learns the opposite of what happened.
 */
export type CorrectionDirection = "earlier" | "later";
