// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Every counter name that may appear on the wire.
 *
 * A CLOSED enum, not a string, and that is the point: a counter name is the one
 * place a free-form label could sneak user data into an otherwise numeric
 * payload ("export.Gudstjeneste 6. april"). The renderer-facing
 * `telemetry_count` command validates against exactly this list and rejects
 * anything else, so the IPC boundary cannot widen it either.
 *
 * The wire strings are dotted namespaces (`area.thing.variant`) so the endpoint
 * can aggregate by prefix.
 */
export type CounterName = "recording.started.manual" | "recording.started.scheduled" | "recording.stopped" | "recording.preroll.started" | "recording.selftest" | "editor.opened" | "editor.export.mp3" | "editor.export.wav" | "editor.export.flac" | "editor.export.video" | "editor.export.other" | "editor.master.applied" | "editor.chapters.detected" | "transcribe.run" | "companion.build" | "review.published" | "review.discarded" | "publish.feed.generated" | "trash.moved" | "trash.restored" | "streaming.started" | "diagnose.run" | "update.installed" | "cloud.upload.ok";
