// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CounterName } from "./CounterName";

/**
 * One named counter and its value since the last successful send.
 */
export type CounterReport = { name: CounterName, value: number, };
