// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What kind of crash-adjacent event a [`CrashReport`] describes. Mirrors the
 * `src-tauri` crash ring's `kind` field, as a closed set.
 */
export type CrashKind = "panic" | "task_panic" | "task_restart" | "other";
