// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What the crash ring holds — count + newest, not the records themselves. The
 * report is a page a person reads, not a stack-trace archive.
 */
export type CrashSummary = { count: number, 
/**
 * RFC 3339 local timestamp of the newest record, if any.
 */
newest: string | null, 
/**
 * The newest record's message, truncated upstream. Lets the report show
 * WHAT crashed without the user opening a folder.
 */
newestMessage: string | null, };
