// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CrashKind } from "./CrashKind";
import type { TelemetryOs } from "./TelemetryOs";

/**
 * One crash-ring record, projected onto the wire.
 */
export type CrashReport = { 
/**
 * Which of the ring's three kinds this is.
 */
kind: CrashKind, 
/**
 * Unix ms (UTC) the record was written.
 */
at: number, 
/**
 * The app version that crashed — often NOT the version reading the ring,
 * which is exactly why it travels with the record.
 */
appVersion: string, 
/**
 * The OS that crashed.
 */
os: TelemetryOs, 
/**
 * The panic message: scrubbed, redacted, capped at [`MESSAGE_MAX_CHARS`].
 */
message: string, 
/**
 * `file:line:col`, same treatment. `None` for the task-* kinds.
 */
location: string | null, 
/**
 * The supervised task's name, for the task-* kinds.
 */
task: string | null, 
/**
 * Whether a backtrace exists ON THE USER'S MACHINE. The backtrace itself is
 * not sent — see the module docs for why.
 */
backtracePresent: boolean, };
