// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A per-device input-channel pair — which two native device channels feed the
 * LEFT/RIGHT of a stereo recording (e.g. an X32's 16/17). Keyed by device id in
 * [`Settings::device_channels`]; the flat [`Settings::input_channel_l`]/`_r`
 * the recorder reads are DERIVED from this map in [`Settings::validate`].
 * Serialised camelCase to match the Electron `DeviceChannels`.
 */
export type DeviceChannels = { 
/**
 * 0-based device channel routed to the LEFT output. Clamped 0..=31.
 */
channelL: number, 
/**
 * 0-based device channel routed to the RIGHT output. Clamped 0..=31.
 */
channelR: number, };
