// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Severity of a [`DiagnosticFinding`], driving the UI badge + the support triage.
 */
export type DiagnosticSeverity = "ok" | "info" | "warning" | "critical";
