// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiagnosticSeverity } from "./DiagnosticSeverity";

/**
 * A single diagnose result with a STABLE support code. The `code` (e.g.
 * `"SR-AUDIO-01"`) never changes meaning across versions, so a user can read it
 * out and support knows exactly which situation it is — the "fishing" the user
 * asked for. `detail` carries the specifics (device name, free GB, …) and `hint`
 * the concrete next step.
 */
export type DiagnosticFinding = { code: string, severity: DiagnosticSeverity, title: string, detail: string, hint: string, };
