// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiagnosticFinding } from "./DiagnosticFinding";

/**
 * The result the renderer gets back: the report markdown, where it was saved
 * (if anywhere), and the tri-state capture results. Mirrors the non-secret
 * subset of the Electron `DiagnosticsReport`; `clipboardOk` is dropped because
 * the clipboard write is a UI-side concern (`navigator.clipboard`).
 */
export type DiagnosticsReport = { 
/**
 * The full markdown report (rendered by the panel + copied to clipboard).
 */
markdown: string, 
/**
 * Structured findings (the stable error-code system) for the UI to render as
 * a coloured checklist — the actionable summary above the raw markdown.
 */
findings: Array<DiagnosticFinding>, 
/**
 * Absolute path the report was written to, or `None` if the save failed.
 */
savedTo: string | null, 
/**
 * Audio capture test (E2.5): a real ~2 s capture through the recorder's own
 * backend. `None` = not run — see [`Self::capture_probe_skipped`].
 */
captureOk: boolean | null, 
/**
 * Video capture test (E2.5): one real frame from the camera. `None` when
 * video is off or the probe was skipped.
 */
videoOk: boolean | null, 
/**
 * Why the probe did not run, when it did not.
 */
captureProbeSkipped: string | null, };
