// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LastErrorInfo } from "./LastErrorInfo";
import type { RecordingTelemetry } from "./RecordingTelemetry";
import type { SettingsSummary } from "./SettingsSummary";

/**
 * Everything the `src-tauri` layer gathered, ready to be formatted. No secrets
 * can appear here (see [`SettingsSummary`] / module docs).
 */
export type DiagnosticsInput = { 
/**
 * App semver (e.g. `"0.1.0"`).
 */
appVersion: string, 
/**
 * Target OS (`std::env::consts::OS` — `"macos"`, `"windows"`, …).
 */
platform: string, 
/**
 * CPU architecture (`std::env::consts::ARCH`).
 */
arch: string, 
/**
 * First line of `ffmpeg -version`, or `None` when ffmpeg did not resolve.
 */
ffmpegVersion: string | null, 
/**
 * Audio capture device names ffmpeg / cpal enumerated.
 */
audioDevices: Array<string>, 
/**
 * Video capture device names ffmpeg enumerated.
 */
videoDevices: Array<string>, 
/**
 * The non-secret settings summary.
 */
settings: SettingsSummary, 
/**
 * Audio capture test result: `Some(true)`=ok, `Some(false)`=failed,
 * `None`=not tested (the F2.2 default — the live test is Fase-3 hardware).
 */
captureOk: boolean | null, 
/**
 * Video capture test result, same tri-state. `None` when not tested /
 * video disabled.
 */
videoOk: boolean | null, 
/**
 * Free bytes on the save-folder volume, or `None` if it couldn't be read.
 */
freeDiskBytes: number | null, 
/**
 * Whether the save folder is writable, or `None` if not probed.
 */
saveFolderWritable: boolean | null, 
/**
 * Microphone permission: `"authorized"`/`"denied"`/`"not_determined"`/`None`.
 */
micPermission: string | null, 
/**
 * Camera permission, same vocabulary. `None` when not probed / video off.
 */
cameraPermission: string | null, 
/**
 * Which audio engine the recorder LAST used (`"wasapi"`/`"asio"`/
 * `"directshow"`/`"coreaudio"`), or `None` if it hasn't recorded yet.
 */
audioEngine: string | null, 
/**
 * If the modern engine fell back, WHY (human text). `None` = no fallback.
 */
audioEngineFallback: string | null, 
/**
 * ASIO devices seen (Windows + `asio` feature). Empty otherwise.
 */
asioDevices: Array<string>, 
/**
 * The most recent classified recording error written to `last-error.json`.
 */
lastError: LastErrorInfo | null, 
/**
 * Whether the Windows orphan-guard Job Object is active this session.
 */
orphanGuardActive: boolean | null, 
/**
 * Health telemetry of the MOST RECENT recording (drops/xruns/IPC-starvation),
 * read back from `last-recording.json`. `None` = nothing recorded yet. The
 * automatic passive-logging signal that lets the report explain stutter/lag.
 */
lastRecording: RecordingTelemetry | null, 
/**
 * Recent recordings' telemetry (newest last) for a TREND view — so the user
 * pastes a pattern, not a one-off snapshot. Capped upstream (~20).
 */
recordingHistory: Array<RecordingTelemetry>, };
