// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OpenedRecording } from "./OpenedRecording";

/**
 * What the drop handler tells the page: the recording that was dropped, or why
 * it cannot be opened, and where on the window it landed (physical pixels, as
 * the OS gave them) so the page can aim the drop at the zone under the cursor.
 */
export type DroppedRecording = { opened: OpenedRecording | null, 
/**
 * The leading `source_*` code when `opened` is none.
 */
error: string | null, x: number, y: number, };
