// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EditorSegment } from "./EditorSegment";

/**
 * What the renderer sends when the human overrides the sermon auto-pick.
 *
 * The whole segment list travels, not just the two blocks: the record is only
 * interpretable against the alternatives that existed, and the attention
 * heuristics read the music/silence blocks the picker never offers.
 */
export type EditorSermonPickRequest = { 
/**
 * The segments as the UI had them WHEN THE CHOICE WAS MADE — i.e. before
 * the promotion flips the two `type` fields, so `autoIndex` still points at
 * a block the detector labelled `sermon`.
 */
segments: Array<EditorSegment>, 
/**
 * Indices of the blocks the picker offered, in the order it offered them.
 */
candidateIndices: Array<number>, 
/**
 * Index of the DETECTOR's pick — not whatever is promoted right now, which
 * may already be an earlier correction. `None` when it found no sermon.
 */
autoIndex: number | null, 
/**
 * Index of the block the human picked.
 */
chosenIndex: number, 
/**
 * Length of the recording, seconds.
 */
durationSec: number, };
