// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EditorChannelDiagnosis } from "./EditorChannelDiagnosis";

/**
 * The one-click "auto-improve" recommendation: the channel diagnosis plus the
 * vocal-chain + mastering presets to apply for the best out-of-the-box result.
 * The renderer applies these to its export settings in a single click.
 */
export type EditorAutoProcess = { 
/**
 * The channel-balance analysis + recommended repair.
 */
diagnosis: EditorChannelDiagnosis, 
/**
 * Vocal-chain preset id to apply (e.g. `voice-podcast`).
 */
vocalChainPreset: string, 
/**
 * Mastering preset id to apply. EMPTY from [`auto_process`] — one click
 * recommends the vocal chain only; stacking a mastering chain on top of it
 * double-processes (two highpasses, two compressors). Kept in the DTO
 * because the renderer applies whatever it is told, and a future
 * recommender may fill it in.
 */
masterPreset: string, 
/**
 * A short Norwegian summary of what was decided, for a toast/hint.
 */
summary: string, };
