// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The measured loudness the mastering UI shows before/after a preset, mirroring
 * the pass-1 `loudnorm` JSON the Electron mastering flow surfaced.
 */
export type EditorLoudness = { 
/**
 * Measured integrated loudness (LUFS).
 */
inputI: number, 
/**
 * Loudness range.
 */
inputLra: number, 
/**
 * True peak (dBTP).
 */
inputTp: number, 
/**
 * Measurement threshold (LUFS). Carried so an apply can REUSE this
 * measurement instead of re-running the pass that produced it — it is one
 * of the five values `loudnorm`'s linear mode needs.
 */
inputThresh: number, 
/**
 * Suggested gain offset (LU) — the fifth value the linear-mode apply needs.
 */
targetOffset: number, 
/**
 * The preset this was measured against (its target LUFS for the delta UI).
 */
targetLufs: number, };
