// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A decode-progress tick for the three whole-file passes that used to report
 * nothing at all: the waveform decode (`editor://peaks-progress`), the content
 * analysis (`editor://analysis-progress`) and the playback-proxy transcode
 * (`editor://proxy-progress`).
 *
 * `fraction` is 0..1 and monotonically non-decreasing within one pass. It is a
 * measured quantity in every case, not a guess: the two decode passes divide
 * bytes-read by the byte count the probed duration implies (both pipes are a
 * fixed rate — 8 kHz and 16 kHz mono s16le), and the transcode divides
 * ffmpeg's own `out_time` by the same duration.
 *
 * One shape for all three because the renderer treats them identically, and a
 * `phase` field would be inventing a distinction the UI does not draw: each of
 * these is a single pass, named by the surface that started it.
 */
export type EditorDecodeProgress = { fraction: number, };
