// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EditorChannelRepair } from "./EditorChannelRepair";
import type { EditorCutRegion } from "./EditorCutRegion";
import type { EditorProcessing } from "./EditorProcessing";

/**
 * Export request — the cut-plan + a chosen format + optional mastering preset,
 * intro/outro jingles, and title/speaker/description. Mirrors the non-video
 * subset of the Electron `EditorExportParams` the editor UI sent (mp4 video
 * re-encode aside).
 */
export type EditorExportRequest = { inputPath: string, cutRegions: Array<EditorCutRegion>, duration: number, 
/**
 * Output container: `mp3|aac|wav|flac|mp4`.
 */
format: string, 
/**
 * Folder to write into; the seam picks a collision-free name there.
 */
outputFolder: string, 
/**
 * Output bitrate (kbps) for lossy formats; `None` uses the codec default.
 */
bitrate: number | null, 
/**
 * WAV bit depth (16/24); ignored for non-WAV.
 */
bitDepth: number | null, 
/**
 * Optional mastering preset id (a two-pass loudnorm chain is applied first).
 */
masterPreset: string | null, 
/**
 * Optional intro clip prepended to the audio on export (non-mp4 only).
 */
introPath: string | null, 
/**
 * Optional outro clip appended to the audio on export (non-mp4 only).
 */
outroPath: string | null, 
/**
 * Optional peak-normalization gain (dB) applied as a `volume` filter — what
 * the editor's "Normalize" button computes. `None`/`0` is a no-op.
 */
gainDb: number | null, 
/**
 * Optional file title (FFMETADATA `title`).
 */
title: string | null, 
/**
 * Optional speaker (FFMETADATA `artist`).
 */
speaker: string | null, 
/**
 * Optional description (FFMETADATA `comment`).
 */
description: string | null, 
/**
 * One-click vocal-chain preset id (`voice-light|voice-podcast|
 * voice-noisy-room`). Resolved server-side; ignored when `processing` is set.
 */
vocalChainPreset: string | null, 
/**
 * Full per-stage vocal-chain config. Overrides `vocalChainPreset`. The chain
 * runs BEFORE the mastering loudnorm (tone/dynamics first, loudness last).
 */
processing: EditorProcessing | null, 
/**
 * Channel repair to apply. Overrides the repair carried by `processing`/the
 * preset, and applies on its own (without any vocal chain) when set alone.
 */
channelRepair: EditorChannelRepair | null, 
/**
 * Video codec for a video-container export (`h264` default, or `h265`/`hevc`
 * for ~half the size). Ignored for audio formats.
 */
videoCodec: string | null, };
