// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EditorChannelDiagnosis } from "./EditorChannelDiagnosis";

/**
 * The one-click "auto-improve" recommendation: the channel diagnosis plus the
 * vocal-chain + mastering presets to apply for the best out-of-the-box result.
 * The renderer applies these to its export settings in a single click.
 */
export type EditorAutoProcess = { 
/**
 * The channel-balance analysis + recommended repair.
 */
diagnosis: EditorChannelDiagnosis, 
/**
 * Vocal-chain preset id to apply (e.g. `voice-podcast`).
 */
vocalChainPreset: string, 
/**
 * Mastering preset id to apply. EMPTY from [`auto_process`] — one click
 * recommends the vocal chain only; stacking a mastering chain on top of it
 * double-processes (two highpasses, two compressors). Kept in the DTO
 * because the renderer applies whatever it is told, and a future
 * recommender may fill it in.
 */
masterPreset: string, 
/**
 * A short ENGLISH summary of what was decided — a RESERVE, for the log and
 * for a support paste (F2-I18N-R2).
 *
 * The shell does not render it: `SoundStep`'s channel note is built from
 * [`Self::diagnosis`]'s `code` and the profile names the chain, both in
 * the volunteer's own language. Anything that wants the sentence on screen
 * builds it from those two fields, never from this one.
 */
summary: string, };
