// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EditorLoudness } from "./EditorLoudness";

/**
 * A mastering *apply* request — apply (pass 2) `inputPath` to `outputPath`,
 * tracked by `jobId` so the UI can [`master_cancel`] it. Mirrors `master-apply`.
 *
 * Pass 1 (the loudness measure) is supplied by the caller in `measurement`
 * whenever it already has one: the mastering panel runs
 * `editor_mastering_analyze` to show "-23.4 LUFS → -16 LUFS" *before* the user
 * presses Apply, and re-measuring the same unchanged file here is a second
 * full-length ffmpeg read of a 90-minute service for a byte-identical answer.
 * Optional for back-compat — absent means "measure it yourself".
 */
export type EditorMasterApplyRequest = { inputPath: string, outputPath: string, presetId: string, 
/**
 * Client-supplied job id for cancellation; the apply is rejected if it is
 * already in flight (duplicate-id guard, via the core JobRegistry).
 */
jobId: string, 
/**
 * Output bitrate (kbps) for lossy formats; `None` uses the codec default.
 */
bitrate: number | null, 
/**
 * A pass-1 loudness measurement of THIS file against THIS preset, from a
 * prior `editor_mastering_analyze`. `None` → the seam measures it itself.
 */
measurement?: EditorLoudness, };
