// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EditorChannelRepair } from "./EditorChannelRepair";
import type { EditorCutRegion } from "./EditorCutRegion";
import type { EditorProcessing } from "./EditorProcessing";

/**
 * Export request — the cut-plan + a chosen format + optional mastering preset,
 * intro/outro jingles, and title/speaker/description. Mirrors the non-video
 * subset of the Electron `EditorExportParams` the editor UI sent (mp4 video
 * re-encode aside).
 */
export type EditorExportRequest = { 
/**
 * The recording to export, as the webview may say it: the File token
 * [`editor_open_recording`]/`editor_open_known` minted (or the drop
 * handler did) for it — never a path. The command layer resolves it into
 * [`ResolvedExport::source`] and hands the seam that, separately.
 *
 * Until finding A2 (PR-C) this was `input_path`, a string the webview
 * chose: with no per-command ACL a compromised webview could point the
 * render at any readable file. An old-shape payload's `inputPath` is now
 * an unknown key serde ignores — and the missing token refuses it.
 */
sourceToken: string, cutRegions: Array<EditorCutRegion>, duration: number, 
/**
 * Output container: `mp3|aac|wav|flac|mp4`.
 */
format: string, 
/**
 * WHERE the export goes, as the webview may say it: `None` = «Samme mappe
 * som opptaket» (next to the source, the default), or the session token
 * `editor_pick_output_folder` minted when the operator picked a folder in
 * a dialog RUST opened. Never a path — see `commands::chosen_paths`.
 *
 * Until finding A2 this was `output_folder: String`, the path the
 * webview's own folder picker answered, and a compromised webview could
 * put any folder there with no dialog at all. An old-shape payload's
 * `outputFolder` is now an unknown key, which serde ignores: it lands
 * nowhere, and that export goes next to its source.
 *
 * The command layer resolves the token into an [`ExportFolder`] and hands
 * it to [`export`] separately, so the seam never sees the token either.
 */
outputFolderToken: string | null, 
/**
 * Output bitrate (kbps) for lossy formats; `None` uses the codec default.
 */
bitrate: number | null, 
/**
 * WAV bit depth (16/24); ignored for non-WAV.
 */
bitDepth: number | null, 
/**
 * Optional mastering preset id (a two-pass loudnorm chain is applied first).
 */
masterPreset: string | null, 
/**
 * Prepend the stored intro clip (`settings.editorIntroPath`) to the audio
 * on export (non-mp4 only). A switch, not a path: Rust reads the clip from
 * the saved settings and re-validates it, so the webview cannot name a file
 * to splice in. No stored clip means no intro, whatever this says.
 */
useIntro: boolean, 
/**
 * The same for the stored outro clip (`settings.editorOutroPath`).
 */
useOutro: boolean, 
/**
 * Optional peak-normalization gain (dB) applied as a `volume` filter — what
 * the editor's "Normalize" button computes. `None`/`0` is a no-op.
 */
gainDb: number | null, 
/**
 * Optional file title (FFMETADATA `title`).
 */
title: string | null, 
/**
 * Optional speaker (FFMETADATA `artist`).
 */
speaker: string | null, 
/**
 * Optional description (FFMETADATA `comment`).
 */
description: string | null, 
/**
 * Optional church name (FFMETADATA `album`) — `settings.churchName`, so an
 * episode is filed under the congregation wherever the tags are read.
 */
album: string | null, 
/**
 * Optional service date as `YYYY-MM-DD` (FFMETADATA `date`). Also the
 * prefix of a titled export's file name — see
 * `sundayrec_core::editor::export_stem`.
 */
date: string | null, 
/**
 * One-click vocal-chain preset id (`voice-light|voice-podcast|
 * voice-noisy-room`). Resolved server-side; ignored when `processing` is set.
 */
vocalChainPreset: string | null, 
/**
 * Full per-stage vocal-chain config. Overrides `vocalChainPreset`. The chain
 * runs BEFORE the mastering loudnorm (tone/dynamics first, loudness last).
 */
processing: EditorProcessing | null, 
/**
 * Channel repair to apply. Overrides the repair carried by `processing`/the
 * preset, and applies on its own (without any vocal chain) when set alone.
 */
channelRepair: EditorChannelRepair | null, 
/**
 * Video codec for a video-container export (`h264` default, or `h265`/`hevc`
 * for ~half the size). Ignored for audio formats.
 */
videoCodec: string | null, };
