// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which normalisation the mastering pass actually performed. Mirrors
 * [`sundayrec_core::mastering::NormalizationMode`] — read out of ffmpeg's
 * pass-2 report, never assumed.
 */
export type EditorLoudnessMode = "linear" | "dynamic";
