// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The waveform peaks the renderer draws. Duration is NOT carried here: the
 * loader takes ffprobe's (via [`EditorMediaInfo`], authoritative — the
 * renderer's `<audio>.duration` can lie on VBR) and only falls back to
 * `peaks.len() / 100` when the probe came up empty.
 */
export type EditorPeaks = { 
/**
 * Max-abs amplitude per bucket, 0..1, at 100 buckets per second
 * (`sundayrec_core::editor::PEAKS_PER_SEC`) — the rate the renderer's
 * waveform indexes against.
 */
peaks: Array<number>, 
/**
 * The sample rate the peaks were decoded at (8 kHz — see core).
 */
sampleRate: number, };
