// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An export progress tick, emitted on the `editor://export-progress` event
 * (the renderer subscribes through the shim channel `editor-export-progress`).
 * `pct` is 0–100 and monotonically non-decreasing within one export; `phase`
 * is a stable CODE the renderer localises — `measuring` (mastering pass 1,
 * which reports no percentage of its own) or `encoding` (the render).
 */
export type EditorExportProgress = { pct: number, phase: string, };
