// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A small, decodable 8 kHz mono WAV for a recording the renderer can't inline-
 * decode (over `EDITOR_INLINE_LIMIT`, or an exotic codec the browser rejects).
 * The renderer decodes this via Web Audio for the waveform + scrub preview;
 * cuts are applied to the ORIGINAL file at export, so this low-rate buffer never
 * affects output quality.
 */
export type EditorAudioExtract = { 
/**
 * 8 kHz mono PCM-WAV bytes (decodable by the renderer's Web Audio API).
 */
bytes: Array<number>, 
/**
 * Duration in seconds (from the extracted 8 kHz sample count).
 */
duration: number, };
