// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EditorLoudnessMode } from "./EditorLoudnessMode";

/**
 * What the mastering actually did to the delivery level (F2-C-B).
 *
 * Present only when a mastering preset ran AND ffmpeg's pass-2 report said
 * which normalisation it performed. Absent is honest: "we did not read it back"
 * is a different answer from "it was linear", and only the receipt knows which
 * of those it can put on screen.
 */
export type EditorExportLoudness = { 
/**
 * What ffmpeg reported doing.
 */
mode: EditorLoudnessMode, 
/**
 * The integrated loudness the export was set to land on — the preset's
 * target, or the quieter one the true-peak ceiling allowed.
 */
achievedLufs: number, 
/**
 * The preset's own target, so the receipt can say what was asked for.
 */
targetLufs: number, 
/**
 * True when the ceiling capped the gain, i.e. `achieved < target` for a
 * reason the user can act on (a hot recording).
 */
peakLimited: boolean, };
