// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EditorExportLoudness } from "./EditorExportLoudness";

/**
 * The outcome of an export: where the file landed, and — with a mastering
 * preset — what happened to the level.
 */
export type EditorExportResult = { outputPath: string, 
/**
 * `None` for an unmastered export, and for a mastered one whose pass-2
 * report we could not read. OPTIONAL on the TS side on purpose: every
 * caller that only wants the path keeps compiling.
 */
loudness?: EditorExportLoudness, };
