// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What the email panel needs to render itself without a failed send: whether
 * this build compiled the `email` feature in at all. Filled by the
 * `src-tauri` shell from the cargo feature.
 */
export type EmailStatus = { 
/**
 * True when the binary was built with `--features email` (the send path is
 * present). A `--no-default-features` build is `false` → the panel shows a
 * calm hint.
 */
featureBuilt: boolean, };
