// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a block was classified as. A closed vocabulary: the detector's `kind`
 * string is mapped INTO this, and anything unrecognised becomes
 * [`FeedbackSegmentKind::Unknown`] rather than being stored verbatim (the same
 * rule the export counter follows — an unrecognised tag must never leak the
 * string).
 */
export type FeedbackSegmentKind = "silence" | "speech" | "music" | "mixed" | "unknown" | "sermon";
