// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FeedbackSegmentKind } from "./FeedbackSegmentKind";

/**
 * One analysed block, as the decision saw it.
 *
 * `index` is the block's position in the segment list the correction was made
 * against — recorded because it is what the UI worked with, and useless on its
 * own: re-analysing a recording renumbers everything. The OFFSETS are the
 * durable identity, which is why every consumer here matches on them.
 */
export type FeedbackSegment = { 
/**
 * Position in the segment list at the time of the correction.
 */
index: number, 
/**
 * Offset from the START OF THE RECORDING, seconds. Never a clock time.
 */
startSec: number, 
/**
 * Offset from the start of the recording, seconds.
 */
endSec: number, durationSec: number, kind: FeedbackSegmentKind, 
/**
 * The classifier's confidence in `kind`, 0..1. `None` when the segment came
 * from a cache written before confidence was carried through.
 */
confidence?: number, };
