// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The image formats the cover-art panels accept.
 *
 * GIF is deliberately absent. It is in the renderer's generic image-picker
 * extension list (shared with the overlay picker, where an animated logo makes
 * sense), but an animated cover image is not something Apple Podcasts, Spotify
 * or any RSS consumer will take, so the thumbnail path must not quietly accept
 * one and produce a broken feed later.
 */
export type ImageFormat = "jpeg" | "png" | "webp";
