// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The most recent recording error, read back from `last-error.json` (written by
 * the recorder on a classified failure). Lets the diagnose tool explain what
 * stopped the previous recording even though it can't see in-process events.
 */
export type LastErrorInfo = { code: string, message: string, timestamp: string, };
