// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TrimTendency } from "./TrimTendency";

/**
 * What the app has noticed, across every recording that still has a
 * `<stem>.feedback.json` beside it. A recording's observations live and die
 * with its sidecar — deleting the recording deletes them, and this summary
 * simply never sees what is not there to read.
 *
 * Every field is a count or a duration; see the module doc for why nothing
 * here is or could become a sentence, a name, or a path.
 */
export type LearningSummary = { 
/**
 * How many sermon-pick corrections are on file, summed across every
 * recording. One [`RecordingFeedback`] holds at most one per detector
 * baseline it was corrected against (see
 * [`crate::feedback::record_sermon_pick`]), so this is genuinely "how
 * many times", not "how many recordings".
 */
sermonPickCorrections: number, 
/**
 * How many trim adjustments are on file, summed the same way.
 */
trimAdjustments: number, startTendency: TrimTendency, 
/**
 * Average seconds moved, in the dominant direction only — `0.0` when
 * [`TrimTendency::Unclear`]. Mixing in the minority-direction samples
 * would understate how far the majority actually moved it.
 */
startAvgAbsDeltaSec: number, endTendency: TrimTendency, endAvgAbsDeltaSec: number, 
/**
 * How many companion-suggestion outcomes are on file (every build's
 * title/description/chapters events, summed across recordings).
 */
companionTotal: number, companionAccepted: number, companionLeftAlone: number, companionRejected: number, 
/**
 * Subset of `companion_accepted` where the taken suggestion was then
 * rewritten — see [`crate::feedback::CompanionSuggestionRecord::edited_after_accept`].
 */
companionEditedAfterAccept: number, };
