// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What the scan found: where the old profile is and how many bytes it holds.
 */
export type LegacyDataInfo = { 
/**
 * Absolute path of the old Electron profile directory.
 */
path: string, 
/**
 * Total size of the files inside it, in bytes.
 */
bytes: number, };
