// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Nudge } from "./Nudge";

/**
 * Everything one install has adjusted about itself. One field per tuning-table
 * row this module can produce evidence for; see the module header for why the
 * level threshold is not among them.
 */
export type LocalNudge = { 
/**
 * Seconds added to the proposed sermon START. Positive = later, matching
 * [`crate::trim_feedback`]'s sign convention exactly, because it is
 * derived from those deltas without re-stating the convention.
 */
sermonStartSec: Nudge, 
/**
 * Seconds added to the proposed sermon END. Positive = later.
 */
sermonEndSec: Nudge, };
