// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The rotating file log's state (E2.3).
 */
export type LogFileInfo = { 
/**
 * Absolute path to the live log file.
 */
path: string, 
/**
 * Its current size, or `None` when it does not exist yet.
 */
sizeBytes: number | null, 
/**
 * Log lines dropped because the writer could not keep up. Non-zero means
 * the log is INCOMPLETE, which anyone reading it needs to know.
 */
droppedLines: number, };
