// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Everything the renderer may say about a manual start — and, on purpose,
 * nothing that names a place on disk.
 *
 * ## Why this exists (security finding E1)
 *
 * Until this type, `start_recording` took a whole [`RecordingOpts`] from the
 * webview. The renderer got it from `plan_recording_opts` and passed it
 * straight back, so `output_path` was a raw renderer string by the time it
 * reached the engine — which creates that path's folder, captures into it,
 * finalises over it and writes a separate-audio sibling next to it. The app
 * has no capability ACL narrowing which commands a page may call, so a
 * compromised renderer could have aimed a recording at any path the user can
 * write to (a login item, a shell profile). The path ratchet could not see it
 * either: it judged parameter NAMES, and `opts` is not path-shaped — the path
 * was one field down.
 *
 * Now the renderer sends only the three things that were ever ITS to decide
 * (the very three `plan_recording_opts` always took), and Rust plans the rest
 * with the same composition as before (`plan_manual_in`). That the opts
 * reaching the engine are byte-identical to what the old round trip
 * delivered, for every legitimate start, is the `golden_manual_*` tests in
 * `src-tauri/src/commands/recorder.rs`.
 *
 * ## Why unknown keys are ignored, not refused
 *
 * No `deny_unknown_fields`, deliberately. A stray key cannot DO anything here
 * — there is no field for it to land in — and refusing it would turn a
 * harmless renderer slip into a recording that does not start on a Sunday.
 * An old-shape payload with an `output_path` in it is simply a request with
 * no name; the tests pin that, too.
 */
export type ManualStartRequest = { 
/**
 * What the operator typed as a name for this take; `None` or blank →
 * the profile's filename pattern. Never a path: `build_filename`
 * sanitises it into one file NAME (separators become `_`).
 */
customName: string | null, 
/**
 * Auto-stop after this many minutes; `None`/`0` = the setting decides
 * (off unless it says otherwise).
 */
maxMinutes: number | null, 
/**
 * The Home video toggle (local UI state, not persisted); `None` = the
 * persisted `video_enabled` decides. A manual video recording lands as
 * `.mp4` only when a camera is configured.
 */
video: boolean | null, };
