// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What the OS says about showing SundayRec's notifications.
 */
export type NotificationPermission = "granted" | "denied" | "unknown";
