// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One adjustment the app has made to itself, with everything needed to say so
 * out loud: how much, whether the clamp stopped it there, and how much evidence
 * is behind it.
 *
 * `value` carries no unit of its own — the field that holds a `Nudge` says
 * which quantity it belongs to, exactly as [`crate::trim_feedback::TrimDeltas`]
 * carries seconds without repeating "seconds" in every doc line. The unit is
 * fixed by the clamp it was built with.
 */
export type Nudge = { 
/**
 * How far the shipped constant is moved. Zero means "not adjusted", which
 * is what the operator sees on every install that has not yet earned one.
 */
value: number, 
/**
 * Whether the clamp is what decided `value`. Reported rather than folded
 * into the number because "we moved it a minute" and "we wanted to move it
 * four minutes and were only allowed one" are different facts about the
 * detector, and only the second one is a reason to look at the recordings.
 */
atLimit: boolean, 
/**
 * Corrections behind `value`. Below [`MIN_CORRECTIONS_FOR_NUDGE`] this is
 * how the operator can see that the app is watching but not yet acting.
 */
samples: number, };
