// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A recording the editor opened: the token every later command names it by,
 * and what the page shows and plays.
 */
export type OpenedRecording = { 
/**
 * Opaque, random, session-scoped — the File token. Hand it back; never
 * parse it.
 */
token: string, 
/**
 * The file's own name («2026-08-02 Gudstjeneste.mp3»), for the heading.
 */
name: string, 
/**
 * The canonical path, plain: what the page SHOWS (the folder it sits in)
 * and what `<audio src>` plays (`asset://` needs an address, and Rust
 * granted the scope to exactly this file). NOT accepted by any command —
 * every one that reads, renders or keeps something for the recording
 * takes `token` and nothing else.
 */
path: string, };
