// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A recording the editor opened: the token every later command names it by,
 * and what the page shows and plays.
 */
export type OpenedRecording = { 
/**
 * Opaque, random, session-scoped — the File token. Hand it back; never
 * parse it.
 */
token: string, 
/**
 * The file's own name («2026-08-02 Gudstjeneste.mp3»), for the heading.
 */
name: string, 
/**
 * The canonical path, plain: what `<audio src>` plays (`asset://`) and what
 * the sidecar commands (`editor_read_sidecar` & co., PR-D) still take.
 * NOT accepted by anything that reads or renders the recording — those
 * take `token` and nothing else.
 */
path: string, };
