// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Podcast/RSS channel configuration (R4 — the Electron `podcast` object as a
 * real settings field). The feed generator (`commands::publish::resolve_channel`)
 * reads THIS — previously it read ten `app_setting` rows
 * (`podcastTitle`, …) that no code path ever wrote, so the feed always
 * rendered the fallbacks whatever the UI said. Defaults for blank/missing
 * values are applied by the READER (blank title → "SundayRec" etc.), matching
 * the old renderer's display fallbacks; here blank simply means unset.
 */
export type PodcastSettings = { 
/**
 * Master switch for the podcast pipeline (feed + prep-and-review).
 */
enabled: boolean, 
/**
 * Which cloud service hosts the audio + feed:
 * `"google-drive"` (default) | `"dropbox"` | `"onedrive"`.
 */
service: string, title: string, description: string, author: string, 
/**
 * ISO 639-1 feed language. Default `"no"`.
 */
language: string, 
/**
 * iTunes category. Default `"Religion & Spirituality"`.
 */
category: string, explicit: boolean, 
/**
 * Church homepage, or `None`.
 */
link: string | null, 
/**
 * Cover art URL (1400–3000 px square), or `None`.
 */
imageUrl: string | null, 
/**
 * Owner contact email (required by Apple), or `None`.
 */
email: string | null, 
/**
 * Set after the first successful publish — what the user submits to
 * Spotify/Apple.
 */
feedUrl: string | null, 
/**
 * Auto-run prep + queue the episode for review after each recording.
 * Default true (the v5.0 pipeline's own default).
 */
autoPrepEnabled: boolean, 
/**
 * Per-church default intro jingle, or `None` (falls back to
 * `editor_intro_path`).
 */
defaultIntroPath: string | null, 
/**
 * Per-church default outro jingle, or `None`.
 */
defaultOutroPath: string | null, 
/**
 * Master preset for the prep pipeline. Default `"speech-clear"`.
 */
defaultMasterPreset: string, };
