// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How the model's per-hop probabilities become ONE score for an analysis frame.
 *
 * The two grids do not line up: Silero answers every [`VAD_HOP_SAMPLES`]
 * samples (32 ms at 16 kHz) and [`crate::audio_analysis`] works in 100 ms
 * frames, so roughly three model outputs land in each frame (3.125 on average —
 * most frames get 3, every eighth gets 4). Something has to pool them, and
 * *which* something is a detection-quality decision, not a formatting one.
 *
 * All three honest candidates are implemented and unit-tested rather than one
 * being picked by taste, because the answer is an empirical question that
 * [`DEFAULT_POOLING`] can only pre-empt, not settle. Changing the default is a
 * one-line edit there plus the test that pins it.
 */
export type PoolingRule = "max" | "mean" | "fraction_over";
