// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PreflightCategory } from "./PreflightCategory";
import type { PreflightCode } from "./PreflightCode";
import type { PreflightSeverity } from "./PreflightSeverity";

/**
 * A single thing the preflight check found. Mirrors the Electron
 * `PreflightFinding` interface field-for-field, plus the [`PreflightCode`] the
 * two localised surfaces render on.
 */
export type PreflightFinding = { severity: PreflightSeverity, category: PreflightCategory, 
/**
 * The code the app localises on. `None` for a finding the SHELL built
 * itself (`app/lib/status/health-findings.ts` raises two of its own from
 * the permission probes) — those already carry text in the user's
 * language, and inventing a code for them here would be a second answer
 * to a question that already has one.
 */
code: PreflightCode | null, 
/**
 * The engine's own wording: ENGLISH, with `params` already filled in.
 * Used verbatim by a reader that does not know [`Self::code`].
 */
message: string, 
/**
 * Interpolation values for the localised sentence (`{gb}`). Same shape and
 * same reason as [`crate::notify::BackendWarning::params`].
 */
params: { [key in string]: string }, };
