// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which part of the pipeline a finding is about. Serialised lowercase to match
 * the Electron `'preroll' | 'wake' | 'disk' | 'device'` union
 * (`preflight.ts:21`, minus `'cloud'`, which left with cloud backup).
 * `Preroll`/`Wake` are reserved for their later phases (pre-roll buffer,
 * wake-from-sleep) and are not raised by the F2.2 plumbing yet — they exist so
 * the type already matches Electron.
 */
export type PreflightCategory = "preroll" | "wake" | "disk" | "device";
