// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What the preflight check found, as a STABLE CODE.
 *
 * Was six hardcoded Norwegian sentences (F2-I18N-R2). The findings are
 * rendered verbatim in the app's preflight card AND in the native
 * notification the scheduler fires half an hour before a service, so the
 * prose was the app's own voice in exactly one of its seven languages.
 *
 * The code is the contract now, and it has TWO catalogues because it has two
 * surfaces — which is the rule, not an exception to it:
 *
 *   • the card: `status.preflightCode.<code>` in `legacy/locales/*.json`,
 *     rendered by `app/state/preflight.ts`;
 *   • the native notification: [`AlertText`] (see [`Self::alert`]), because
 *     Rust cannot reach the renderer's catalogue and a notification is not a
 *     place to be silent.
 *
 * [`Self::as_str`] is the ENGLISH reserve — the log line, and the text field
 * a shell older than the code would fall back on.
 */
export type PreflightCode = "ffmpegMissing" | "deviceMissing" | "folderNotWritable" | "diskLow" | "micDenied" | "cameraDenied";
