// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SegmentType } from "./SegmentType";

/**
 * One analysis segment — the detector's canonical output, for BOTH callers.
 *
 * The `Prep` in the name is historical: this was the review path's shape before
 * E9 unified the two detectors, and it is the wire contract the renderer already
 * imports (`PrepAnalysisSegment.ts`). Renaming it would move a generated binding
 * and every `.ts` import of it for no behavioural gain, so the name stays and
 * this note explains it.
 *
 * camelCase on the wire, mirroring the renderer type, which is itself the mirror
 * of `audio-analysis.ts` `AnalysisSegment`.
 */
export type PrepAnalysisSegment = { startSec: number, endSec: number, durationSec: number, type: SegmentType, confidence: number, avgRmsDb: number, label: string, };
