// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SegmentType } from "./SegmentType";

/**
 * One analysis segment — the detector's canonical output, for BOTH callers.
 *
 * The `Prep` in the name is historical: this was the review path's shape before
 * E9 unified the two detectors, and it is the wire contract the renderer already
 * imports (`PrepAnalysisSegment.ts`). Renaming it would move a generated binding
 * and every `.ts` import of it for no behavioural gain, so the name stays and
 * this note explains it.
 *
 * camelCase on the wire, mirroring the renderer type, which is itself the mirror
 * of `audio-analysis.ts` `AnalysisSegment`.
 */
export type PrepAnalysisSegment = { startSec: number, endSec: number, durationSec: number, type: SegmentType, confidence: number, 
/**
 * Mean frame RMS in dBFS, or `f64::NEG_INFINITY` for a block with no finite
 * frame RMS at all — see [`crate::audio_analysis`]'s `close`, which returns
 * exactly that for digital silence.
 *
 * JSON has no `-Infinity`, so `serde_json` writes any non-finite float as
 * `null` — and a plain `f64` field REFUSES to read `null` back. That is a
 * lossy round-trip through every store this segment is persisted in, and
 * the review queue is one of them: a single silent block made the whole
 * queue blob unparseable, which `load_queue` then read as "no queue".
 * `null` therefore has to mean here what it meant when it was written.
 */
avgRmsDb: number, label: string, };
