// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PrerollEngineKind } from "./PrerollEngineKind";

/**
 * The pre-roll status surfaced to the UI ("preroll aktiv").
 */
export type PrerollStatus = { 
/**
 * Whether the rolling capture loop is currently active.
 */
active: boolean, 
/**
 * Which engine is running it (or would, when idle) — diagnostics for a rig
 * session, so "pre-roll is on" and "pre-roll is on the OLD path" are
 * distinguishable without reading a log.
 */
engine: PrerollEngineKind, 
/**
 * The native buffer's negotiated input-channel count while it is streaming
 * (0 = idle, retrying, or classic). This is the width of the `vu://levels`
 * packets it emits.
 */
channels: number, };
