// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which implementation is (or would be) running the buffer.
 */
export type PrerollEngineKind = "native" | "classic";
