// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A harvested, trimmed pre-roll clip ready to prepend to a recording.
 *
 * `raw_path` is the *trimmed* clip produced by the harvest in the
 * format the caller requested — the recording's own capture format, so the
 * prepend is a lossless `-c copy` (today PCM `.wav`; the raw rolling capture it
 * came from is consumed + deleted during harvest). `trim_ms` and
 * `start_offset_ms` are the core mat's verdict, kept on the clip for
 * diagnostics.
 */
export type PrerollClip = { 
/**
 * Absolute path to the trimmed clip.
 */
raw_path: string, 
/**
 * Milliseconds of audio kept (the prepend length).
 */
trim_ms: number, 
/**
 * Where in the raw capture the kept window started (ffmpeg `-ss`), for
 * diagnostics; the trimmed clip already begins here.
 */
start_offset_ms: number, };
