// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The outcome of one retention pass: how many recordings were MOVED into the
 * Papirkurv. (Until the owner decision below, the field was `deleted` and the
 * pass hard-deleted — see the history on `recordings_prune`.)
 */
export type PruneSummary = { 
/**
 * Recordings whose file was moved into the trash this pass. Their history
 * rows stay — the trash's own purge is the one moment a row dies.
 */
moved: number, 
/**
 * Whether retention is disabled (`autoDeleteDays <= 0`) — the UI shows a
 * hint rather than "0 moved".
 */
disabled: boolean, };
