// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The channel «Legg ut» opens. Serialised lowercase; `none` hides the panel.
 *
 * SoundCloud is the default because it is what most churches told us they
 * distribute sermons with. The others are the channels they named next.
 */
export type PublishTarget = "soundcloud" | "youtube" | "spotify" | "custom" | "none";
