// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QualityReason } from "./QualityReason";
import type { SelfTestVerdict } from "./SelfTestVerdict";

/**
 * One finished recording's health, projected onto the wire.
 *
 * Numbers and enums only: no filename, no folder, no device. What a support
 * engineer needs from a recording is whether the audio arrived, and these are
 * the numbers that answer it.
 */
export type QualityReport = { 
/**
 * Unix ms (UTC) the session ended.
 */
at: number, 
/**
 * Wall-clock length of the session.
 */
durationSec: number, 
/**
 * Seconds the session should have captured.
 */
expectedSec: number, 
/**
 * Seconds actually present in the delivered file(s).
 */
measuredSec: number, 
/**
 * Percent of expected audio missing from the delivery.
 */
lossPct: number, 
/**
 * Combined gap (missing duration + interior silence).
 */
gapSec: number, drops: number, dups: number, xruns: number, 
/**
 * Live-levels IPC messages dropped on a full channel.
 */
levelsDropped: number, 
/**
 * ffmpeg capture back-pressure warnings seen.
 */
captureDropLines: number, 
/**
 * Non-levels reader messages dropped on a full channel.
 */
msgsDropped: number, 
/**
 * Samples the native engine's callback dropped on ring overrun.
 */
ringOverrunSamples: number, 
/**
 * Whether the session ended cleanly.
 */
exitOk: boolean, 
/**
 * The Pass/Warn/Fail verdict, when one was computed.
 */
verdict: SelfTestVerdict | null, 
/**
 * WHICH conditions fired — codes, never the Norwegian sentences.
 */
reasons: Array<QualityReason>, };
