// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * WHY a recording's self-test reached its verdict — the machine-readable
 * counterpart of [`crate::selftest::SelfTestReport::reasons`], which is prose.
 *
 * One variant per `escalate(...)` call in
 * [`crate::selftest::selftest_verdict`], in the same order, so
 * [`derive_reason_codes`] is a faithful re-reading of that function's decisions
 * from the numbers it recorded.
 */
export type QualityReason = "no-audio-captured" | "silent-take" | "large-gap" | "many-drops" | "forced-rate-mismatch" | "small-gap" | "low-signal" | "some-drops" | "clean";
