// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SelfTestReport } from "./SelfTestReport";

/**
 * Health counters accumulated AUTOMATICALLY during a real recording — the
 * passive-logging path. The recorder's stderr reader feeds every line through
 * [`RecordingTelemetry::observe_line`] and flags a starved IPC channel via
 * [`RecordingTelemetry::note_levels_dropped`]; the host stamps `duration_sec`/
 * `timestamp`/`exit_ok` at session end and persists it. Surfaced in the
 * diagnose report so the user pastes a *trend*, not a guess.
 *
 * ## Accumulation semantics, field by field (E6.3)
 *
 * A session is not one ffmpeg process. A split opens a new deliverable with a
 * new capture process; a reconnect opens a new `_rN` fragment with another.
 * Two different kinds of counter live in here, and they aggregate differently:
 *
 * - **`drops`/`dups` are ffmpeg's own CUMULATIVE counters**, re-printed in full
 *   on every progress line. Within one process the right fold is `max` (take
 *   the latest/highest); ACROSS processes the right fold is `sum` — the second
 *   process's `drop=` restarts at zero and knows nothing about the first's.
 *   Folding with `max` for the whole session, as this used to, reported the
 *   worst SINGLE segment: a 3-hour service that dropped 40 frames in each of
 *   four segments reported 40, not 160. The fix is a per-process window
 *   ([`RecordingTelemetry::seal_process`], called at each segment end) whose
 *   maximum is added to the session total.
 * - **`xruns`, `capture_drop_lines`, `levels_dropped`, `msgs_dropped` are EVENT
 *   counts** — one increment per matching stderr line / dropped message. They
 *   already accumulate correctly across any number of processes, because
 *   nothing about them restarts; they were checked for the same flaw and do not
 *   have it.
 * - **`ring_overrun_samples`, `native_frames_sec`, `expected_sec`,
 *   `measured_sec`** are summed by the engine per segment / per deliverable and
 *   are likewise correct.
 */
export type RecordingTelemetry = { 
/**
 * Frames ffmpeg DISCARDED across the whole session (an avfoundation/USB
 * overflow signal): the sum over capture processes of each one's final
 * `drop=`. Excludes the process currently running — see
 * [`Self::drops_total`].
 */
drops: bigint, 
/**
 * Frames ffmpeg DUPLICATED across the whole session (a clock-mismatch
 * signal), summed over capture processes like [`Self::drops`].
 */
dups: bigint, 
/**
 * xrun/overrun-class stderr lines seen — the direct stutter signal.
 */
xruns: bigint, 
/**
 * Times the live-levels IPC `try_send` hit a FULL channel — the direct
 * renderer/IPC-starvation signal ("recording mode lags"). A rising count
 * means the UI couldn't keep up and back-pressure was building.
 */
levelsDropped: bigint, 
/**
 * Capture back-pressure / sample-drop warnings from ffmpeg's own stderr
 * ([`CAPTURE_DROP_PHRASES`]) — the direct "samples were thrown away" count.
 */
captureDropLines: bigint, 
/**
 * Non-levels reader messages (Progress/Silence/Error/Started) dropped on a
 * full channel. Observability loss only — NEVER capture loss (the whole
 * point of the all-`try_send` reader).
 */
msgsDropped: bigint, 
/**
 * Wall-clock seconds the session SHOULD have captured (sum of segment
 * spans, host-stamped at finalize). 0 until the truth-measurement runs.
 */
expectedSec: number, 
/**
 * Media seconds actually present in the delivered file(s) (ffprobe at
 * finalize). THE truth the 2026-07-31 incident lacked: wall clock said
 * 46.6 s while the file held 20.4 s and everything reported "clean".
 */
measuredSec: number, 
/**
 * Percent of expected audio MISSING from the delivery (startup-allowance
 * adjusted). ≥ [`DURATION_LOSS_FAIL_PCT`] ⇒ degraded + user-visible.
 */
lossPct: number, 
/**
 * Samples the NATIVE engine's real-time callback dropped on ring overrun
 * (whole frames' worth of f32 samples). The native analogue of the
 * xrun/capture-drop stderr counters; 0 on the ffmpeg path.
 */
ringOverrunSamples: bigint, 
/**
 * Media seconds implied by the native writer's EXACT frame count
 * (frames/rate, summed per segment). Capture-side cross-check against the
 * ffprobe-measured `measured_sec`: disagreement localizes a fault to
 * capture vs delivery instantly. 0.0 on the ffmpeg path.
 */
nativeFramesSec: number, 
/**
 * The Pass/Warn/Fail verdict computed at session end (None on legacy rows).
 */
report: SelfTestReport | null, 
/**
 * Wall-clock length of the recording (host-stamped at session end).
 */
durationSec: number, 
/**
 * ISO-8601 local timestamp of session end (host-stamped).
 */
timestamp: string, 
/**
 * Whether the session ended cleanly (Stopped) vs Failed (host-stamped).
 */
exitOk: boolean, };
