// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChannelMode } from "./ChannelMode";

/**
 * Options for [`RecorderEngine::start`].
 *
 * Minted in Rust ONLY — by `recorder::opts::build_opts_in`, for the
 * scheduler and for a manual start alike — and never deserialized from the
 * renderer. That is why this type is `Serialize` (the read-only preview,
 * `plan_recording_opts`, returns it) but deliberately NOT `Deserialize`:
 * every `#[tauri::command]` parameter must be `Deserialize`, so without it
 * no command can take these opts, and `output_path` — the file the engine
 * creates its folder for, captures into and finalises over — cannot come
 * from the webview. Until the fix for finding E1 `start_recording` took
 * exactly this struct, and with it a raw renderer string as the place to
 * write. A compile-time assertion beside the struct (in
 * `recorder/engine/payloads.rs`) turns re-adding the derive into a build
 * error.
 */
export type RecordingOpts = { 
/**
 * Stored microphone/mixer name to fuzzy-match against the enumerated audio
 * devices. Empty → first/default device.
 */
audio_device_name: string, 
/**
 * Stored camera name to match against video devices. `None` → audio-only.
 */
video_device_name: string | null, 
/**
 * Absolute output file path the (first) segment is written to.
 */
output_path: string, 
/**
 * User opted into stop-on-silence.
 */
stop_on_silence: boolean, 
/**
 * Silence threshold in dB (clamped by the core filter builder).
 */
silence_threshold_db: number | null, 
/**
 * Minutes of continuous silence before stop-on-silence fires (1–120).
 */
silence_timeout_minutes: number, 
/**
 * Output channel layout / downmix mode (stereo, mono-L, mono-R, mono-mix).
 */
channel_mode: ChannelMode, 
/**
 * Explicit 0-based device input channel → LEFT output (multi-channel mixers).
 * `None` keeps the `channel_mode` default routing.
 */
input_channel_l: number | null, 
/**
 * Explicit 0-based device input channel → RIGHT output. See `input_channel_l`.
 */
input_channel_r: number | null, 
/**
 * Capture sample rate in Hz, or `None` to capture at the device's NATIVE
 * rate (omit `-ar` — the anti-resample / anti-choppiness fix). Resolved from
 * `Settings::sample_rate_mode` via `resolved_sample_rate()`.
 */
sample_rate: number | null, 
/**
 * Output bitrate in kbps for lossy codecs (mp3/aac); ignored by wav/flac.
 */
bitrate_kbps: number, 
/**
 * Rotate to a fresh segment every N minutes (0 = off).
 */
split_minutes: number, 
/**
 * Auto-stop the whole session after N minutes (0 = off).
 */
manual_max_minutes: number, 
/**
 * Emit the live L/R level meters (`astats`) during capture? When `false`,
 * the levels filter is dropped to keep capture maximally stable.
 */
live_levels: boolean, 
/**
 * For a VIDEO recording, also extract a standalone audio sidecar file next to
 * the finished video. No-op for audio-only recordings (the main file already
 * is the audio).
 */
keep_separate_audio: boolean, 
/**
 * The extension/container for the separate audio sidecar (e.g. `"wav"`),
 * chosen from `Settings::separate_audio_format`. Drives the extract codec via
 * the shared `audio_encode_args` seam.
 */
separate_audio_format: string, 
/**
 * Windows escape hatch: force the legacy ffmpeg DirectShow audio path instead
 * of the modern cpal (WASAPI/ASIO) capture. Default `false`. No effect on macOS.
 */
classic_directshow: boolean, 
/**
 * Escape hatch: force the legacy ffmpeg audio capture (avfoundation) instead
 * of the native cpal engine. Default `false`. See `Settings::classic_ffmpeg_audio`.
 */
classic_ffmpeg_audio: boolean, };
