// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Health counters accumulated AUTOMATICALLY during a real recording — the
 * passive-logging path. The recorder's stderr reader feeds every line through
 * [`RecordingTelemetry::observe_line`] and flags a starved IPC channel via
 * [`RecordingTelemetry::note_levels_dropped`]; the host stamps `duration_sec`/
 * `timestamp`/`exit_ok` at session end and persists it. Surfaced in the
 * diagnose report so the user pastes a *trend*, not a guess.
 *
 * `drops`/`dups` track the max ffmpeg `drop=`/`dup=` seen (cumulative within one
 * ffmpeg process); across a split (a new process) this is the max single
 * segment, not the sum — an acceptable under-report for the common single-take
 * sermon. `xruns`/`levels_dropped` are event counts that accumulate correctly.
 */
export type RecordingTelemetry = { 
/**
 * Max ffmpeg `drop=` (discarded frames; an avfoundation/USB-overflow signal).
 */
drops: bigint, 
/**
 * Max ffmpeg `dup=` (duplicated frames; a clock-mismatch signal).
 */
dups: bigint, 
/**
 * xrun/overrun-class stderr lines seen — the direct stutter signal.
 */
xruns: bigint, 
/**
 * Times the live-levels IPC `try_send` hit a FULL channel — the direct
 * renderer/IPC-starvation signal ("recording mode lags"). A rising count
 * means the UI couldn't keep up and back-pressure was building.
 */
levelsDropped: bigint, 
/**
 * Wall-clock length of the recording (host-stamped at session end).
 */
durationSec: number, 
/**
 * ISO-8601 local timestamp of session end (host-stamped).
 */
timestamp: string, 
/**
 * Whether the session ended cleanly (Stopped) vs Failed (host-stamped).
 */
exitOk: boolean, };
