// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CompanionSuggestionRecord } from "./CompanionSuggestionRecord";
import type { SermonPickCorrection } from "./SermonPickCorrection";
import type { TrimAdjustment } from "./TrimAdjustment";

/**
 * The `<stem>.feedback.json` file: everything the human has told us about ONE
 * recording.
 *
 * Named for the file, not for its first collection: it started life holding
 * sermon picks and now holds three unrelated families of correction, and a
 * reader who takes "sermon" in the type name at face value will look for the
 * companion events somewhere else.
 */
export type RecordingFeedback = { schema: number, 
/**
 * Oldest first, bounded by [`MAX_SERMON_PICK_CORRECTIONS`]. One record per
 * detector baseline; see [`record_sermon_pick`].
 */
sermonPicks: Array<SermonPickCorrection>, 
/**
 * Oldest first, bounded by [`MAX_TRIM_ADJUSTMENTS`]. One record per app
 * version; see [`record_trim_adjustment`].
 */
trimAdjustments: Array<TrimAdjustment>, 
/**
 * Oldest first, bounded by [`MAX_COMPANION_SUGGESTION_EVENTS`]. Genuinely
 * append-only; see [`record_companion_suggestion`].
 */
companionSuggestions: Array<CompanionSuggestionRecord>, };
