// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where a subscription is in the double opt-in.
 *
 * Three states and no fourth: "unsubscribed" is the ABSENCE of a record, not a
 * state within one. A fourth value meaning "gone" would be a record the pump's
 * gate still counts as enrolled, i.e. a machine that keeps a dead subscription
 * alive forever.
 */
export type RelaySubscriptionState = "pending" | "confirmed" | "suppressed";
