// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RelaySubscriptionState } from "./RelaySubscriptionState";

/**
 * What the settings panel needs to render the relay card — and nothing more.
 *
 * No token, no hash, no sub id. The panel's job is to show a state, an address
 * and how many messages are waiting; handing the webview a credential it has no
 * use for would be a credential in one more place.
 */
export type RelaySubscriptionStatus = { 
/**
 * Whether this build has a relay endpoint at all. `false` means the URL or
 * the write key was missing at compile time, and the panel should say so
 * rather than offering a button that queues rows nothing will ever send.
 */
endpointBuilt: boolean, 
/**
 * `None` when this machine has never enrolled an address.
 */
state: RelaySubscriptionState | null, 
/**
 * The enrolled address, echoed back so the panel does not have to remember
 * what was typed in a previous session.
 */
address: string | null, enrolledAt: number | null, confirmedAt: number | null, 
/**
 * How many messages are waiting in the outbox.
 */
queued: number, };
