// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The facts the impure shell feeds in after running the capture + analysis.
 */
export type SelfTestFacts = { 
/**
 * The `-t N` duration we asked ffmpeg to capture.
 */
expectedSec: number, 
/**
 * Actual captured duration (last `time=`, or ffprobe of the file).
 */
measuredSec: number, drops: bigint, dups: bigint, xruns: bigint, 
/**
 * Output file size in bytes (the "did it capture anything" floor).
 */
sizeBytes: number, 
/**
 * Strongest `astats` RMS dB over the take, or `None` if unmeasured.
 */
strongestRmsDb: number | null, 
/**
 * Total interior-silence seconds from a `silencedetect` pass over the take.
 */
silenceTotalSec: number, 
/**
 * The device's native sample rate (if known).
 */
nativeSampleRate: number | null, 
/**
 * The sample rate the settings FORCE (`Some` ⇒ ffmpeg resamples; a mismatch
 * with `native_sample_rate` is a known choppiness cause).
 */
forcedSampleRate: number | null, };
