// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SelfTestVerdict } from "./SelfTestVerdict";

/**
 * The self-test result: a verdict, the human reasons, and the flat numbers the
 * diagnose report + the user paste verbatim.
 */
export type SelfTestReport = { 
/**
 * `true` unless the verdict is `Fail` — i.e. capture works (possibly with a
 * warning). Drives the diagnose `capture_ok` tri-state.
 */
ok: boolean, verdict: SelfTestVerdict, reasons: Array<string>, drops: bigint, dups: bigint, xruns: bigint, expectedSec: number, measuredSec: number, 
/**
 * Combined gap = missing duration + interior silence.
 */
gapSec: number, rmsDb: number | null, 
/**
 * `silence_total_sec / measured_sec` (0 when nothing captured).
 */
silenceRatio: number, sizeBytes: number, nativeSampleRate: number | null, forcedSampleRate: number | null, };
