// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QualityReason } from "./QualityReason";
import type { SelfTestVerdict } from "./SelfTestVerdict";

/**
 * The self-test result: a verdict, the human reasons, and the flat numbers the
 * diagnose report + the user paste verbatim.
 */
export type SelfTestReport = { 
/**
 * `true` unless the verdict is `Fail` — i.e. capture works (possibly with a
 * warning). Drives the diagnose `capture_ok` tri-state.
 */
ok: boolean, verdict: SelfTestVerdict, 
/**
 * WHY, in Norwegian prose, rendered verbatim by whoever shows the report.
 *
 * ⚠️ These sentences are written HERE, in Rust, and the quality banner
 * showed them word for word in all seven UI languages — a German volunteer
 * read «Svakt signal — vurder å øke gain». Rust cannot translate them
 * (the UI language lives in the settings row, and this function is pure),
 * so the fix is to stop asking it to: [`Self::reason_codes`] carries the
 * same list as machine-readable codes for the renderer to localise. The
 * prose stays for the diagnose report and the paste-into-a-support-mail
 * path, where a stable Norwegian sentence is the point.
 */
reasons: Array<string>, 
/**
 * The same conditions as [`Self::reasons`], as codes — one per prose line,
 * in the same order, set by the same branch.
 *
 * Not re-derived from the numbers afterwards (that is
 * [`crate::telemetry::derive_reason_codes`]'s job, and a second reading is
 * a second thing to drift): every `escalate` here pushes the sentence and
 * its code together, so "the codes follow the prose 1:1" is true by
 * construction and asserted over a fact matrix by
 * `every_prose_reason_carries_its_code`.
 *
 * `#[serde(default)]` so a report stored before the field existed still
 * deserialises — as an empty list, which is honestly "this payload predates
 * codes" rather than "nothing was wrong".
 */
reasonCodes: Array<QualityReason>, drops: bigint, dups: bigint, xruns: bigint, expectedSec: number, measuredSec: number, 
/**
 * Combined gap = missing duration + interior silence.
 */
gapSec: number, rmsDb: number | null, 
/**
 * `silence_total_sec / measured_sec` (0 when nothing captured).
 */
silenceRatio: number, sizeBytes: number, nativeSampleRate: number | null, forcedSampleRate: number | null, };
