// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One ranked highlight passage. `time` is where it starts in the recording,
 * `score` is the heuristic rank (higher = more quotable), kept for the UI to
 * show "why" and for stable ordering.
 */
export type SermonHighlight = { time: number, end: number, text: string, score: number, };
