// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CompanionChapter } from "./CompanionChapter";
import type { SermonHighlight } from "./SermonHighlight";
import type { SummarySource } from "./SummarySource";

/**
 * The complete companion result surfaced in the renderer panel. Chapters +
 * highlights are always deterministic on-device output; `summary`/`title`
 * are LLM-suggested when available, else the local extractive fallback.
 */
export type SermonCompanion = { 
/**
 * Suggested episode title (Norwegian). Short.
 */
title: string, 
/**
 * Norwegian summary, a few sentences.
 */
summary: string, 
/**
 * Where `summary`/`title` came from.
 */
summarySource: SummarySource, 
/**
 * Chapter markers (scripture refs + enumeration points + topic shifts),
 * sorted by time, on the original recording timeline.
 */
chapters: Array<CompanionChapter>, 
/**
 * 2–4 ranked quotable passages.
 */
highlights: Array<SermonHighlight>, 
/**
 * The transcript language the detectors ran under (`"no"` / `"en"`).
 */
language: string, };
