// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SermonPickCorrection } from "./SermonPickCorrection";

/**
 * The `<stem>.feedback.json` file: everything the human has told us about ONE
 * recording.
 */
export type SermonFeedback = { schema: number, 
/**
 * Append-list, oldest first, bounded by [`MAX_SERMON_PICK_CORRECTIONS`].
 */
sermonPicks: Array<SermonPickCorrection>, };
