// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FeedbackSegment } from "./FeedbackSegment";

/**
 * One sermon-pick correction: the detector's answer, the human's answer, and
 * the evidence the choice was made among.
 *
 * **This record must NEVER carry audio, transcript or sermon text, the
 * recording's name, any filesystem path, or a wall-clock time of day — a time
 * of day plus a duration fingerprints one specific service at one specific
 * church. Offsets within the recording only.** That is why there is no
 * timestamp field here and no ordering field beyond the position in
 * [`SermonFeedback::sermon_picks`]: a record that cannot say WHEN cannot
 * identify WHO. Anyone extending this type inherits the rule, and cannot
 * violate it without first deleting this paragraph.
 */
export type SermonPickCorrection = { 
/**
 * The block the detector picked. `None` when it found no sermon at all —
 * itself a strong signal, and the reason this is not a plain field.
 */
auto?: FeedbackSegment, 
/**
 * The block the human picked instead.
 */
chosen: FeedbackSegment, 
/**
 * The blocks the picker offered — what the decision was made AMONG. A
 * correction is only interpretable against the alternatives that existed.
 */
candidates: Array<FeedbackSegment>, 
/**
 * [`crate::prep::AttentionReason`] codes that fired for this recording.
 * Codes, never their Norwegian sentences.
 */
attention: Array<string>, 
/**
 * Length of the recording, seconds. A duration, not a time.
 */
recordingDurationSec: number, 
/**
 * The app version that produced the auto-pick being corrected — without it
 * a record cannot be attributed to the detector that made the mistake.
 */
appVersion: string, };
