// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChannelMode } from "./ChannelMode";
import type { CloudServicePrefs } from "./CloudServicePrefs";
import type { DeviceChannels } from "./DeviceChannels";
import type { FileFormat } from "./FileFormat";
import type { FilenamePattern } from "./FilenamePattern";
import type { PodcastSettings } from "./PodcastSettings";
import type { SampleRate } from "./SampleRate";
import type { ScheduleSlot } from "./ScheduleSlot";
import type { SpecialRecording } from "./SpecialRecording";
import type { StreamDestinationStored } from "./StreamDestinationStored";
import type { UpdateChannel } from "./UpdateChannel";

/**
 * The complete (Fase-1 subset) settings model.
 *
 * Every field carries `#[serde(default)]` so a partial or older JSON blob
 * deserialises by filling in the per-field [`Default`] — this is the Electron
 * `store.get(key, default)` semantics, see [`Settings::from_json_merged`].
 * Numeric ranges are enforced separately by [`Settings::validate`].
 */
export type Settings = { 
/**
 * UI language code (e.g. `"no"`, `"en"`), or `None` to follow the OS.
 */
language: string | null, 
/**
 * Has the app ever been launched? Gates first-run behaviour.
 */
hasLaunched: boolean, 
/**
 * Has the user completed onboarding?
 */
onboardingDone: boolean, 
/**
 * Stored capture device id (browser `MediaDeviceInfo.deviceId` heritage).
 */
deviceId: string | null, 
/**
 * Stored capture device human-readable name (the device-match moat input).
 */
deviceName: string | null, 
/**
 * Per-DEVICE channel routing, keyed by device id (R4). This is the SOURCE
 * the channel grid writes; the flat `input_channel_l`/`_r` the recorder
 * reads are derived from it for the selected device in
 * [`Settings::validate`], so switching devices switches routing with it
 * (the api-shim bridge used to do this flattening renderer-side).
 */
deviceChannels: { [key in string]: DeviceChannels }, 
/**
 * Capture video (camera) alongside audio? Default false (audio-only is the
 * common church-recording case).
 */
videoEnabled: boolean, 
/**
 * Stored camera human-readable name — the device-match moat input for video
 * (matched with [`crate::device_enum::find_best_video_device_match`]).
 */
videoDeviceName: string | null, 
/**
 * Last-known avfoundation index for the chosen camera. A fallback for when
 * the name lookup fails (e.g. after a reconnect); the name match wins when
 * it succeeds. dshow cameras are addressed by name, so this stays `None`.
 */
videoDeviceIndex: number | null, 
/**
 * Capture resolution tag: `"480p"` | `"720p"` | `"1080p"` | `"2160p"` (4K).
 * Default `"720p"`.
 */
videoResolution: string, 
/**
 * Capture frame rate (fps). Valid 1..=120, default 30.
 */
videoFramerate: number, 
/**
 * Recording video container: `"mp4"` (default) | `"mov"`. Both are
 * QuickTime/ISO containers that take H.264/H.265 + AAC and `+faststart`.
 */
videoContainer: string, 
/**
 * Recording video codec: `"h264"` (default, universal) | `"h265"` (HEVC,
 * ~half the size; for live 4K a hardware encoder is recommended).
 */
videoCodec: string, 
/**
 * Recording video encoder backend: `"hardware"` (default — VideoToolbox on
 * macOS — realtime + low CPU, so the live preview/meters stay snappy and live
 * 4K H.265 is feasible) | `"software"` (libx264/5 — max compression
 * efficiency, but pegs the CPU and makes the live monitoring lag). Ignored
 * off macOS (always falls back to software).
 */
videoEncoder: string, 
/**
 * Mirror the camera horizontally (preview + recording). Default false.
 * Electron `videoFlip` — handy for front-facing / mirrored stage cameras.
 */
videoFlip: boolean, 
/**
 * Recording video bitrate in kbps; 0 = auto from resolution (the default).
 * Non-zero values clamp to 500..=50000 in `validate()`. NOTE: today only
 * the UI reads this (the bitrate control + Home's info strip) — the
 * capture pipeline does not consume it yet; it is persisted so the
 * operator's choice survives until it does.
 */
videoBitrate: number, 
/**
 * Output muxing: `"combined"` (one A/V file) | `"separate"` (split files).
 * Default `"combined"`.
 */
outputMode: string, 
/**
 * Also keep the standalone high-quality audio file next to a combined MP4?
 */
keepSeparateAudio: boolean, 
/**
 * Windows ONLY escape hatch: force the legacy ffmpeg **DirectShow** audio
 * capture instead of the modern cpal (WASAPI/ASIO) path. Default `false` —
 * cpal is the standard Windows capture (more stable, full multichannel via
 * ASIO). Flip on only if cpal misbehaves on a specific rig. No effect on macOS.
 */
classicDirectshow: boolean, 
/**
 * Escape hatch: force the legacy **ffmpeg** audio capture (avfoundation on
 * macOS) instead of the native cpal engine that records the WAV directly.
 * Default `false` — the native engine is the standard path (avfoundation
 * measurably drops samples below ffmpeg's observability; the 2026-08-01
 * rebuild). Flip on only if the native engine misbehaves on a specific rig;
 * scheduled for removal once the rig has verified 0 % loss.
 */
classicFfmpegAudio: boolean, 
/**
 * Escape hatch: force the legacy **ffmpeg** pre-roll buffer (a 90-second
 * rolling avfoundation/dshow capture) instead of the native cpal one.
 * Default `false` — the native buffer holds the device with the same stack
 * the recorder uses, harvests its clip by byte copy, and doubles as the
 * `vu://levels` emitter so the meters and the buffer can coexist. Flip on
 * only if the native buffer misbehaves on a specific rig.
 */
classicFfmpegPreroll: boolean, 
/**
 * Container/codec for the standalone audio file extracted alongside a video
 * recording when `keep_separate_audio` is on. Default `Wav` (lossless, the
 * safe choice for a "keep the clean audio" sidecar).
 */
separateAudioFormat: FileFormat, 
/**
 * Use a single ffmpeg process for A/V to eliminate sync drift? Default true.
 */
avSync: boolean, 
/**
 * Input channel layout.
 */
channels: ChannelMode, 
/**
 * Explicit 0-based input channel to record into the LEFT output channel.
 * `None` keeps the `channels`-mode default routing. Set for multi-channel
 * mixers (e.g. an X32) where you want to record specific channels (17 & 18).
 * Clamped 0..=31 in `validate()`. Only honoured for `ChannelMode::Stereo`.
 */
inputChannelL: number | null, 
/**
 * Explicit 0-based input channel to record into the RIGHT output channel.
 * See [`Settings::input_channel_l`].
 */
inputChannelR: number | null, 
/**
 * Sample rate in Hz. Valid 8000..=192000, default 48000. KEPT for
 * back-compat with exported/old profiles; the RECORDER no longer reads it —
 * it uses [`Settings::resolved_sample_rate`] (driven by `sample_rate_mode`).
 */
sampleRate: number, 
/**
 * How the capture sample rate is chosen. `Auto` (default) captures at the
 * device's native rate (no resample → no choppiness); the explicit variants
 * force a rate. This is what the recorder actually consults.
 */
sampleRateMode: SampleRate, 
/**
 * Input gain as a percentage. Valid 0..=200, default 100.
 */
inputVolume: number, 
/**
 * Is the equalizer enabled?
 */
eqEnabled: boolean, 
/**
 * Bass EQ gain in dB. Valid -24..=24, default 0.
 */
eqBass: number, 
/**
 * Mid EQ gain in dB. Valid -24..=24, default 0.
 */
eqMid: number, 
/**
 * Treble EQ gain in dB. Valid -24..=24, default 0.
 */
eqTreble: number, 
/**
 * Is the compressor enabled?
 */
compEnabled: boolean, 
/**
 * Compressor threshold in dBFS. Valid -60..=0, default -24.
 */
compThreshold: number, 
/**
 * Compressor ratio. Valid 1..=100, default 4.
 */
compRatio: number, 
/**
 * Compressor attack in ms. Valid 0.1..=2000, default 10.
 */
compAttack: number, 
/**
 * Compressor release in ms. Valid 1..=9000, default 200.
 */
compRelease: number, 
/**
 * Is the limiter enabled? Default true.
 */
limiterEnabled: boolean, 
/**
 * Limiter ceiling in dBFS. Valid -10..=0, default -1.
 */
limiterCeiling: number, 
/**
 * Output file format. Default mp3.
 */
format: FileFormat, 
/**
 * Bitrate (kbps) as a string, matching the Electron `'192'` heritage.
 */
bitrate: string, 
/**
 * Filename generation pattern. Default `date`.
 */
filenamePattern: FilenamePattern, 
/**
 * Folder recordings are written to, or `None` for the default location.
 */
saveFolder: string | null, 
/**
 * Auto-delete recordings older than N days. Valid 0..=3650, 0 = off.
 */
autoDeleteDays: number, 
/**
 * Stop the recording after a sustained silent stretch?
 */
stopOnSilence: boolean, 
/**
 * Silence detection threshold in dBFS. Valid -90..=0, default -50.
 */
silenceThreshold: number, 
/**
 * Minutes of silence before auto-stop. Valid 1..=120, default 5.
 */
silenceTimeoutMinutes: number, 
/**
 * Auto-split interval in minutes. Valid 0..=480, 0 = off.
 */
splitMinutes: number, 
/**
 * Run ffmpeg `silenceremove` on the output (trim leading/trailing silence)?
 */
trimSilence: boolean, 
/**
 * Auto-stop manual recordings after N minutes. Valid 0..=1440, 0 = off.
 */
manualMaxMinutes: number, 
/**
 * Pre-roll buffer in seconds. Valid 0..=60, 0 = off.
 */
preRollSeconds: number, 
/**
 * Advanced opt-in for the ROLLING pre-roll buffer (R4). Distinct from
 * `pre_roll_seconds` on purpose and NOT derivable from it: the buffer is a
 * continuous background capture on the recording microphone, so a user who
 * picked a pre-roll length but never flipped this stays un-armed — deriving
 * it from `pre_roll_seconds > 0` would silently start that capture for
 * them. The renderer's `preroll-lifecycle.ts` is the gatekeeper that reads
 * it. Default false.
 */
prerollEnabled: boolean, 
/**
 * Show the live L/R level meters during recording? Default true. When off,
 * the recorder drops the `astats` levels filter from its ffmpeg chain — the
 * meter's per-frame stderr can starve capture on a loaded machine, so turning
 * the meters off trades the display for maximum capture stability.
 */
showLiveLevels: boolean, 
/**
 * Reminder notification N minutes before a scheduled recording.
 * Valid 0..=60, 0 = off.
 */
reminderMinutes: number, 
/**
 * Launch the app at OS login?
 */
launchAtLogin: boolean, 
/**
 * Minimise to the system tray instead of quitting? Default true.
 */
minimizeToTray: boolean, 
/**
 * Wake the machine from sleep for scheduled recordings? Default true.
 */
wakeFromSleep: boolean, 
/**
 * Require confirmation before stopping an in-progress recording? Default true.
 */
protectRecording: boolean, 
/**
 * Weekly recurring recording windows. Empty by default. The scheduler
 * engine turns these into start/stop/reminder/preflight timers; see
 * [`crate::schedule`] for the decision logic.
 */
slots: Array<ScheduleSlot>, 
/**
 * One-off dated recordings (concerts, special services). Empty by default.
 * Auto-pruned 7 days after they end ([`crate::schedule::prune_specials`]).
 */
specialRecordings: Array<SpecialRecording>, 
/**
 * Congregation/church name. Drives the `church` filename pattern and the
 * localized "church" labels. Empty string = unset (matches the Electron
 * `''` default, not `null`). See `store.ts` `churchName: ''`.
 */
churchName: string, 
/**
 * Person responsible for recordings (shown in diagnostics + email alerts).
 * Empty string = unset (Electron `responsiblePerson: ''`).
 */
responsiblePerson: string, 
/**
 * Fire a native notification when a scheduled recording starts? Default true.
 */
notifyStart: boolean, 
/**
 * Fire a native notification when a recording stops? Default true.
 */
notifyStop: boolean, 
/**
 * Chat webhook URL (Slack/Discord/Teams). Empty = unset.
 */
webhookUrl: string, 
/**
 * Also POST the webhook on warnings (not just errors)? Default false.
 */
webhookOnWarning: boolean, 
/**
 * Per-URL opt-in for a webhook on the LOCAL network (E1.4).
 *
 * The webhook URL is fully user-controlled and its response is discarded —
 * a blind SSRF unless something says no. The default policy blocks
 * loopback/private/link-local addresses, but a church legitimately
 * webhooks a LAN device (a booth control panel, a Home Assistant box that
 * lights the "ON AIR" sign), so the settings UI asks out loud and sets this
 * flag for the URL the operator confirmed. Re-typing a different address
 * clears it — this is an opt-in for ONE address, not a mode.
 */
webhookAllowLocal: boolean, 
/**
 * Send an email when a recording fails / a scheduled one is missed?
 */
emailOnError: boolean, 
/**
 * Recipient address for alert emails. Empty = unset (Electron `''`).
 */
emailAddress: string, 
/**
 * SMTP host (blank = use the Gmail transport instead). Electron `emailSmtp`.
 */
emailSmtp: string, 
/**
 * SMTP port. Valid 1..=65535, default 587. Electron `emailSmtpPort: 587`.
 */
emailSmtpPort: number, 
/**
 * SMTP username. Empty = unset (Electron `emailSmtpUser: ''`). The PASSWORD
 * is intentionally absent — it is stored in the OS keychain by the `email`
 * seam, never persisted to the settings bag.
 */
emailSmtpUser: string, 
/**
 * Explicit envelope/`From:` address for alert mail. Empty = derive it, which
 * is what every pre-existing config does: the renderer used to synthesise
 * `emailSmtpUser || recipient` client-side. Providers increasingly reject a
 * `From:` that isn't the authenticated identity (or a verified alias), and
 * the login username is not always a mailbox — SendGrid wants `apikey`,
 * Fastmail/Migadu use `user@domain` handles — so the address has to be
 * settable on its own. The derivation stays as the fallback (see
 * `commands::email::resolve_from_address`) so old configs keep working
 * untouched.
 */
emailSmtpFrom: string, 
/**
 * Path to an intro clip prepended on export, or `None`. Electron used
 * `undefined`; we keep it `Option` so an unset value stays absent.
 */
editorIntroPath: string | null, 
/**
 * Path to an outro clip appended on export, or `None`.
 */
editorOutroPath: string | null, 
/**
 * Use the Apple **VideoToolbox** hardware encoder for the editor's VIDEO
 * export? Default `false` — software x264/x265 is the quality-per-bit
 * reference and works on every machine, so hardware stays opt-in. macOS
 * only: on Windows/Linux the flag is ignored (VideoToolbox does not exist
 * there), and even on macOS a hardware render that fails is retried once
 * with the software args, so the toggle can never make an export
 * unavailable — only faster.
 */
editorHwEncode: boolean, 
/**
 * Persisted stream destinations, WITHOUT keys (keys live in the OS
 * keychain via `stream_set_key`; `has_key` is the only trace here).
 */
streamDestinations: Array<StreamDestinationStored>, 
/**
 * Default stream quality tag: `"480p"` | `"720p"` (default) | `"1080p"`.
 */
streamResolution: string, 
/**
 * Default stream framerate: 25 | 30 (default). Normalised in `validate()`.
 */
streamFramerate: number, 
/**
 * Optional video-bitrate override in kbps; `None` = auto from resolution.
 */
streamVideoBitrate: number | null, 
/**
 * Live overlay configurations, persisted as OPAQUE JSON. The overlay
 * vocabulary (type/source/chroma-key/crop) is renderer-owned — see the
 * hand-written `OverlayConfig` in `legacy/types/index.ts` — and differs
 * from [`crate::overlay::OverlayConfig`] (the ffmpeg builder's input), so
 * the backend persists without interpreting. Malformed JSON costs this
 * field only (lenient), never the blob.
 */
streamOverlays: Array<unknown>, 
/**
 * Google Drive backup preferences, or `None` when never configured.
 */
cloudGoogleDrive: CloudServicePrefs | null, 
/**
 * Dropbox backup preferences.
 */
cloudDropbox: CloudServicePrefs | null, 
/**
 * OneDrive backup preferences.
 */
cloudOneDrive: CloudServicePrefs | null, 
/**
 * Podcast/RSS channel configuration. See [`PodcastSettings`].
 */
podcast: PodcastSettings, 
/**
 * Download and install updates automatically? Default true.
 */
autoUpdate: boolean, 
/**
 * Which release feed to follow (E7). Default [`UpdateChannel::Stable`];
 * `Beta` is opted into per machine and is never inherited from an imported
 * profile's neighbour fields — an unreadable value lands on stable.
 */
updateChannel: UpdateChannel, 
/**
 * Prompt to open the editor after a recording finishes? Default true.
 */
askOpenEditor: boolean, 
/**
 * May the app move its own proposed sermon boundaries toward what THIS
 * operator keeps correcting them to (E10)?
 *
 * Default [`crate::local_adaptivity::DEFAULT_LOCAL_ADAPTIVITY_ENABLED`],
 * which is where the argument for that default lives — it is a decision
 * about what a Sunday looks like, not a serde detail, so it is not spelled
 * `false` here where the reasoning could not follow it.
 *
 * Off means the shipped detector, exactly: the offsets stay at zero, the
 * corrections are still recorded, and the System tab still shows what they
 * say. Turning it back off, or pressing Nullstill, restores that
 * immediately.
 */
localAdaptivity: boolean, };
