// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChannelMode } from "./ChannelMode";
import type { DeviceChannels } from "./DeviceChannels";
import type { FileFormat } from "./FileFormat";
import type { FilenamePattern } from "./FilenamePattern";
import type { SampleRate } from "./SampleRate";
import type { ScheduleSlot } from "./ScheduleSlot";
import type { SpecialRecording } from "./SpecialRecording";
import type { UpdateChannel } from "./UpdateChannel";

/**
 * The complete (Fase-1 subset) settings model.
 *
 * Every field carries `#[serde(default)]` so a partial or older JSON blob
 * deserialises by filling in the per-field [`Default`] — this is the Electron
 * `store.get(key, default)` semantics, see [`Settings::from_json_merged`].
 * Numeric ranges are enforced separately by [`Settings::validate`].
 */
export type Settings = { 
/**
 * UI language code (e.g. `"no"`, `"en"`), or `None` to follow the OS.
 */
language: string | null, 
/**
 * Has the user completed onboarding?
 */
onboardingDone: boolean, 
/**
 * Stored capture device id (browser `MediaDeviceInfo.deviceId` heritage).
 */
deviceId: string | null, 
/**
 * Stored capture device human-readable name (the device-match moat input).
 */
deviceName: string | null, 
/**
 * Per-DEVICE channel routing, keyed by device id (R4). This is the SOURCE
 * the channel grid writes; the flat `input_channel_l`/`_r` the recorder
 * reads are derived from it for the selected device in
 * [`Settings::validate`], so switching devices switches routing with it
 * (the api-shim bridge used to do this flattening renderer-side).
 */
deviceChannels: { [key in string]: DeviceChannels }, 
/**
 * Capture video (camera) alongside audio? Default false (audio-only is the
 * common church-recording case).
 */
videoEnabled: boolean, 
/**
 * Stored camera human-readable name — the device-match moat input for video
 * (matched with [`crate::device_enum::find_best_video_device_match`]).
 */
videoDeviceName: string | null, 
/**
 * Last-known avfoundation index for the chosen camera. A fallback for when
 * the name lookup fails (e.g. after a reconnect); the name match wins when
 * it succeeds. dshow cameras are addressed by name, so this stays `None`.
 */
videoDeviceIndex: number | null, 
/**
 * Mirror the camera horizontally (preview + recording). Default false.
 * Electron `videoFlip` — handy for front-facing / mirrored stage cameras.
 * Kept: it is a per-machine preference the Home preview toggle persists.
 */
videoFlip: boolean, 
/**
 * Also keep the standalone high-quality audio file next to a combined MP4?
 * Default TRUE (R4): the renderer's default has always been «behold også
 * ren lydfil», and the api-shim bridge synced that `true` into sqlite on
 * every boot — so `true` is the deployed behaviour on every install. The
 * old `false` here was only ever visible to code reading defaults before
 * the first bridge sync.
 */
keepSeparateAudio: boolean, 
/**
 * Windows ONLY escape hatch: force the legacy ffmpeg **DirectShow** audio
 * capture instead of the modern cpal (WASAPI/ASIO) path. Default `false` —
 * cpal is the standard Windows capture (more stable, full multichannel via
 * ASIO). Flip on only if cpal misbehaves on a specific rig. No effect on macOS.
 */
classicDirectshow: boolean, 
/**
 * Escape hatch: force the legacy **ffmpeg** audio capture (avfoundation on
 * macOS) instead of the native cpal engine that records the WAV directly.
 * Default `false` — the native engine is the standard path (avfoundation
 * measurably drops samples below ffmpeg's observability; the 2026-08-01
 * rebuild). Flip on only if the native engine misbehaves on a specific rig;
 * scheduled for removal once the rig has verified 0 % loss.
 */
classicFfmpegAudio: boolean, 
/**
 * Escape hatch: force the legacy **ffmpeg** pre-roll buffer (a 90-second
 * rolling avfoundation/dshow capture) instead of the native cpal one.
 * Default `false` — the native buffer holds the device with the same stack
 * the recorder uses, harvests its clip by byte copy, and doubles as the
 * `vu://levels` emitter so the meters and the buffer can coexist. Flip on
 * only if the native buffer misbehaves on a specific rig.
 */
classicFfmpegPreroll: boolean, 
/**
 * Input channel layout.
 */
channels: ChannelMode, 
/**
 * Explicit 0-based input channel to record into the LEFT output channel.
 * `None` keeps the `channels`-mode default routing. Set for multi-channel
 * mixers (e.g. an X32) where you want to record specific channels (17 & 18).
 * Clamped 0..=31 in `validate()`. Only honoured for `ChannelMode::Stereo`.
 */
inputChannelL: number | null, 
/**
 * Explicit 0-based input channel to record into the RIGHT output channel.
 * See [`Settings::input_channel_l`].
 */
inputChannelR: number | null, 
/**
 * How the capture sample rate is chosen. `Auto` (default) captures at the
 * device's native rate (no resample → no choppiness); the explicit variants
 * force a rate. This is what the recorder actually consults.
 */
sampleRateMode: SampleRate, 
/**
 * Output file format. Default mp3.
 */
format: FileFormat, 
/**
 * Bitrate (kbps) as a string, matching the Electron `'192'` heritage.
 */
bitrate: string, 
/**
 * Filename generation pattern. Default `date`.
 */
filenamePattern: FilenamePattern, 
/**
 * Folder recordings are written to, or `None` for the default location.
 */
saveFolder: string | null, 
/**
 * Auto-delete recordings older than N days. Valid 0..=3650, 0 = off.
 */
autoDeleteDays: number, 
/**
 * Stop the recording after a sustained silent stretch?
 */
stopOnSilence: boolean, 
/**
 * Silence detection threshold in dBFS. Valid -90..=0, default -50.
 */
silenceThreshold: number, 
/**
 * Minutes of silence before auto-stop. Valid 1..=120, default 5.
 */
silenceTimeoutMinutes: number, 
/**
 * Auto-split interval in minutes. Valid 0..=480, 0 = off.
 */
splitMinutes: number, 
/**
 * Auto-stop manual recordings after N minutes. Valid 0..=1440, 0 = off.
 */
manualMaxMinutes: number, 
/**
 * Pre-roll buffer in seconds. Valid 0..=60, 0 = off. Default **15** (P1b).
 *
 * This is the ONE control the redesigned Advanced screen shows for
 * pre-roll, and 0 on it means off. It defaults to 15 because the owner's
 * choice for «Frivilligen først» is «pre-roll on and invisible»: the
 * twelve seconds between «the service started» and «somebody pressed
 * Start» are the ones nobody can record twice.
 *
 * A profile written before this change carries its own value (usually 0)
 * and keeps it — only a profile with no key at all, i.e. a fresh install,
 * gets 15.
 */
preRollSeconds: number, 
/**
 * ⚠️ **DEPRECATED — stored, never read.** Kept only so an existing profile
 * survives a round-trip through `settings_save` unchanged.
 *
 * It was the advanced opt-in for the ROLLING pre-roll buffer (R4), and the
 * doc here used to name `preroll-lifecycle.ts` as its gatekeeper. That
 * renderer is gone: the redesigned Advanced screen shows the SECONDS and
 * only the seconds, so the seconds had to become the switch — otherwise a
 * screen saying «15 sekunder» would buffer nothing. `app/state/preroll.ts`
 * derives `enabled` from `pre_roll_seconds > 0`, and telemetry's
 * `WireSettings::preroll_enabled` derives it the same way. Nothing reads
 * THIS field, in Rust or in the shell.
 *
 * The old reasoning — "not derivable, or a user who picked a length but
 * never flipped the switch would get a background capture they never asked
 * for" — was answered by removing the second control instead: the length
 * IS the asking now. See `docs/APP-SHELL.md` («Forhåndsbufferen er ÉN
 * kontroll nå»).
 *
 * Do NOT delete the field. Stored profiles carry `prerollEnabled`, and
 * `Settings` deserialises strictly enough that dropping a key nobody reads
 * is churn with a migration attached. It costs one bool.
 */
prerollEnabled: boolean, 
/**
 * Reminder notification N minutes before a scheduled recording.
 * Valid 0..=60, 0 = off.
 */
reminderMinutes: number, 
/**
 * Launch the app at OS login?
 */
launchAtLogin: boolean, 
/**
 * Wake the machine from sleep for scheduled recordings? Default true.
 */
wakeFromSleep: boolean, 
/**
 * Require confirmation before stopping an in-progress recording? Default true.
 */
protectRecording: boolean, 
/**
 * Is the weekly plan ARMED? Default `true`.
 *
 * P1b. Before this field an empty `slots` list was the only spelling of
 * "automatic recording is off", so the UI's off-switch had to DELETE the
 * time — a switch that throws away data it does not show. The flag
 * separates "armed" from "configured": turning it off keeps the times and
 * stops the planning.
 *
 * `default = true` and not `false` is the half that matters for existing
 * installs: a profile written before this field has no key for serde to
 * read, and `false` would silently disarm every church that already had a
 * Sunday slot — the exact failure this app exists to prevent. A fresh
 * profile has no slots anyway, so `true` there arms nothing.
 *
 * Only WEEKLY slots are gated. `special_recordings` are dated one-offs
 * somebody entered by hand for a specific concert; the level-1 switch is
 * about the recurring plan and never silently cancels those.
 */
autoRecordEnabled: boolean, 
/**
 * Weekly recurring recording windows. Empty by default. The scheduler
 * engine turns these into start/stop/reminder/preflight timers; see
 * [`crate::schedule`] for the decision logic.
 *
 * ⚠️ Read them through [`Settings::active_slots`], never directly: that is
 * the one place `auto_record_enabled` is honoured. The claim was false for
 * a while — both wake commands read this field raw, so a machine with «Ta
 * opp automatisk» OFF still woke at 10:50 on a Sunday for a recording the
 * scheduler would refuse to make, and `wake_verify` then reported the
 * wakes it had itself cancelled as missing.
 *
 * The ONE deliberate raw reader is [`crate::telemetry::WireSettings`]'s
 * `slot_count`, which reports what is CONFIGURED and carries
 * `auto_record_enabled` beside it (see that field's doc). Anything else
 * that reads `slots` directly is a bug in waiting.
 */
slots: Array<ScheduleSlot>, 
/**
 * One-off dated recordings (concerts, special services). Empty by default.
 * Auto-pruned 7 days after they end ([`crate::schedule::prune_specials`]).
 */
specialRecordings: Array<SpecialRecording>, 
/**
 * Congregation/church name. Drives the `church` filename pattern and the
 * localized "church" labels. Empty string = unset (matches the Electron
 * `''` default, not `null`). See `store.ts` `churchName: ''`.
 */
churchName: string, 
/**
 * Person responsible for recordings (shown in diagnostics + email alerts).
 * Empty string = unset (Electron `responsiblePerson: ''`).
 */
responsiblePerson: string, 
/**
 * Fire a native notification when a scheduled recording starts? Default true.
 */
notifyStart: boolean, 
/**
 * Fire a native notification when a recording stops? Default true.
 */
notifyStop: boolean, 
/**
 * Send an email when a recording fails / a scheduled one is missed?
 */
emailOnError: boolean, 
/**
 * Recipient address for alert emails. Empty = unset (Electron `''`).
 */
emailAddress: string, 
/**
 * SMTP host. Blank = no transport at all (the Gmail-OAuth alternative left
 * with the cloud-backup OAuth client). Electron `emailSmtp`.
 */
emailSmtp: string, 
/**
 * SMTP port. Valid 1..=65535, default 587. Electron `emailSmtpPort: 587`.
 */
emailSmtpPort: number, 
/**
 * SMTP username. Empty = unset (Electron `emailSmtpUser: ''`). The PASSWORD
 * is intentionally absent — it is stored in the OS keychain by the `email`
 * seam, never persisted to the settings bag.
 */
emailSmtpUser: string, 
/**
 * Explicit envelope/`From:` address for alert mail. Empty = derive it, which
 * is what every pre-existing config does: the renderer used to synthesise
 * `emailSmtpUser || recipient` client-side. Providers increasingly reject a
 * `From:` that isn't the authenticated identity (or a verified alias), and
 * the login username is not always a mailbox — SendGrid wants `apikey`,
 * Fastmail/Migadu use `user@domain` handles — so the address has to be
 * settable on its own. The derivation stays as the fallback (see
 * `commands::email::resolve_from_address`) so old configs keep working
 * untouched.
 */
emailSmtpFrom: string, 
/**
 * Send a receipt e-mail via the relay when a PLANNED (scheduled)
 * recording finishes? Default off. Independent of `email_on_error` and
 * the SMTP fields above: the receipt travels through
 * `sunday-telemetry`'s relay (`notify.sundaysuite.app`), never through
 * SMTP, and is gated in the UI on a CONFIRMED relay subscription (A5) —
 * this field only remembers whether the toggle is on. Deliberately kept
 * out of `WireSettings`, matching the `updateChannel` precedent
 * (`telemetry.rs:975-978`): the relay subscription record
 * (`notify.relay` in the `app_setting` bag) is per-machine state, not a
 * diagnostic fact worth reporting.
 */
emailReceiptEnabled: boolean, 
/**
 * Path to an intro clip prepended on export, or `None`. Electron used
 * `undefined`; we keep it `Option` so an unset value stays absent.
 */
editorIntroPath: string | null, 
/**
 * Path to an outro clip appended on export, or `None`.
 */
editorOutroPath: string | null, 
/**
 * Download and install updates automatically? Default true.
 */
autoUpdate: boolean, 
/**
 * Which release feed to follow (E7). Default [`UpdateChannel::Stable`];
 * `Beta` is opted into per machine and is never inherited from an imported
 * profile's neighbour fields — an unreadable value lands on stable.
 */
updateChannel: UpdateChannel, 
/**
 * Prompt to open the editor after a recording finishes? Default true.
 */
askOpenEditor: boolean, };
