// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A non-secret summary of the user's settings for the report. EVERY field here
 * is safe to print. Secrets (cloud tokens, e-mail/SMTP credentials, stream
 * keys) are intentionally absent — see the module docs: the report cannot leak
 * what the type cannot hold.
 */
export type SettingsSummary = { language: string | null, deviceName: string | null, channels: string, sampleRate: number, 
/**
 * The sample-rate MODE that actually drives capture: `"auto"` (native, no
 * `-ar`) or a forced `"r44100"/"r48000"/"r96000"`. A forced rate that
 * doesn't match the device resamples and can cause stutter.
 */
sampleRateMode: string, inputVolume: number, format: string, bitrate: string, filenamePattern: string, videoEnabled: boolean, videoDeviceName: string | null, stopOnSilence: boolean, silenceThreshold: number, splitMinutes: number, trimSilence: boolean, autoDeleteDays: number, saveFolder: string | null, };
