// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ShadowComparison } from "./ShadowComparison";
import type { ShadowSettings } from "./ShadowSettings";

/**
 * One shadow-mode run: what the neural detector would have produced, measured
 * against what the app actually did, and the configuration that produced it.
 *
 * ## Why a machine-vs-machine record lives in a file about human corrections
 *
 * It does not belong here by SUBJECT — nobody told us anything, two detectors
 * merely differed. It belongs here by every other property: it is per
 * recording, it is bounded, it inherits the privacy rule below whole, and it
 * shares the sidecar's lifecycle, so a recording deleted or moved takes its
 * shadow observations with it exactly as it takes the corrections. The A/B
 * harness also wants ONE file per recording, not two. The module header's
 * "three collections" is now four, and this is the odd one; that is the note.
 *
 * ## Why this stays on the machine
 *
 * **Nothing here goes to telemetry, deliberately, against the programme's own
 * plan.** The consent text the owner approved covers crash reports, quality
 * data and feature-usage counters. A disagreement between two detectors is
 * none of those three — it is a fourth category, and sending it would be
 * collecting something nobody agreed to, however anonymous the numbers look.
 * The A/B harness needs these locally anyway, which is where they are. If
 * central aggregation is ever wanted it is a new consent decision in a later
 * stage, not a quiet addition to an existing payload: see
 * `crate::telemetry::corrections::banded_corrections` for the projection
 * that reads this file, which does not read this collection.
 *
 * ## Privacy — the same rule as [`SermonPickCorrection`], inherited whole
 *
 * No audio, no transcript, no sermon text, no recording name, no filesystem
 * path, and **no wall-clock time** — a time of day plus a duration fingerprints
 * one service at one church. Durations, offsets within the recording, counts,
 * closed enums and codes. There is no field on this type or on
 * [`ShadowComparison`] any of the forbidden things could occupy, and anyone
 * extending either inherits the rule.
 */
export type ShadowObservation = { 
/**
 * How far apart the two pipelines ended up. Carried as the whole
 * [`ShadowComparison`] rather than flattened, so the sign conventions
 * inside it are stated in exactly one place.
 */
comparison: ShadowComparison, 
/**
 * The pooling rule and thresholds this run used. Without it a record cannot
 * be attributed to a configuration, and a corpus that cannot separate
 * configurations cannot tell whether changing one helped.
 */
settings: ShadowSettings, 
/**
 * The app version whose heuristic and whose model produced the comparison.
 */
appVersion: string, };
