// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ShadowSpan } from "./ShadowSpan";
import type { TrimDeltas } from "./TrimDeltas";

/**
 * How far apart the heuristic and the shadow ended up on one recording.
 *
 * **Durations and offsets only.** No audio, no transcript, no sermon text, no
 * recording name, no path, no wall-clock time — the same rule
 * [`crate::feedback::SermonPickCorrection`] states at length, and for the same
 * reason: a time of day plus a duration identifies one service at one church.
 * There is no field here any of those could occupy.
 */
export type ShadowComparison = { 
/**
 * Length of the recording, seconds. A duration, not a time.
 */
recordingDurationSec: number, heuristicSegmentCount: number, shadowSegmentCount: number, 
/**
 * Seconds both pipelines called speech.
 */
speechAgreedSec: number, 
/**
 * Seconds only the heuristic called speech — where the model took speech
 * away.
 */
speechOnlyHeuristicSec: number, 
/**
 * Seconds only the shadow called speech — where the model found speech the
 * heuristic missed.
 */
speechOnlyShadowSec: number, 
/**
 * The block each pipeline would OFFER — [`Detection::offered`], i.e. what
 * the operator would have seen marked. `None` only when the recording holds
 * no speech at all.
 *
 * The strict pick is not stored separately because it is recoverable:
 * `no_sermon_block` / `speech_at_start` appear in `attention` if and only if
 * the strict search came up empty, and when it did not, the offer IS the
 * strict pick.
 */
heuristicSermon?: ShadowSpan, shadowSermon?: ShadowSpan, 
/**
 * How far the shadow moved each sermon boundary, `shadow − heuristic`.
 *
 * Reuses [`TrimDeltas`] so the sign convention lives in exactly one place
 * (positive = LATER; see that module) instead of being restated here and
 * eventually inverted. `None` when either side has no block to compare.
 */
sermonDeltas?: TrimDeltas, 
/**
 * [`AttentionReason`] codes each pipeline raised. Codes, never their
 * Norwegian sentences — the rule [`crate::detect::AttentionReason`] states.
 */
heuristicAttention: Array<string>, shadowAttention: Array<string>, };
