// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One sermon block, as offsets within the recording.
 *
 * Inherits [`crate::feedback::SermonPickCorrection`]'s privacy rule whole: two
 * offsets and a confidence, no name, no path, no time of day.
 */
export type ShadowSpan = { 
/**
 * Offset from the START OF THE RECORDING, seconds. Never a clock time.
 */
startSec: number, endSec: number, confidence: number, };
