// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PoolingRule } from "./PoolingRule";

/**
 * Everything a shadow run is configured by — and therefore everything a stored
 * observation has to name in order to be interpretable.
 *
 * Carried whole into [`crate::feedback::ShadowObservation`] rather than copied
 * field by field, so a sweep that varies one knob cannot produce records that
 * disagree about which knob moved.
 */
export type ShadowSettings = { pooling: PoolingRule, 
/**
 * Pooled score at or above which the frame reads as speech.
 */
frameSpeechThreshold: number, 
/**
 * Per-hop threshold for [`PoolingRule::FractionOver`]. Stored even when the
 * rule ignores it: a record that omitted it would be ambiguous the moment
 * somebody compared a `fraction_over` sweep against a `max` one.
 */
hopSpeechThreshold: number, };
