// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One live-stream destination as PERSISTED — the stream key is deliberately
 * absent (it lives in the OS keychain via `stream_set_key`; `has_key` is the
 * only trace it leaves here, so the UI can show «•••• (lagret)»). Mirrors the
 * Electron `StreamDestinationStored` field-for-field.
 */
export type StreamDestinationStored = { id: string, name: string, rtmpUrl: string, enabled: boolean, 
/**
 * Whether a stream key is stored in the keychain for this destination.
 */
hasKey: boolean, };
