// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A keep-range (sermon bounds) — the span the detector proposes to trim to,
 * and the unit the trim-feedback + local-adaptivity modules measure in.
 */
export type SuggestedTrim = { startSec: number, endSec: number, };
