// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How the summary/title were produced — drives the UI badge so the operator
 * knows whether prose came from the optional model or the offline fallback.
 */
export type SummarySource = "llm" | "local";
