// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AudioBackendKind } from "./AudioBackendKind";

/**
 * One entry in the unified, backend-tagged input-device list the picker renders.
 * ASIO devices and the host's cpal (WASAPI/CoreAudio) devices share this one
 * shape so the frontend renders them identically, differing only in the badge.
 */
export type TaggedAudioInput = { 
/**
 * Identifier the recorder addresses (device name today).
 */
id: string, 
/**
 * Human-readable device name.
 */
name: string, 
/**
 * Which backend this device is reached through (drives the UI badge).
 */
backend: AudioBackendKind, 
/**
 * Number of input channels (drives the L/R channel selector).
 */
inputChannels: number, 
/**
 * Standard sample rates (Hz) the device supports.
 */
sampleRates: Array<number>, 
/**
 * Whether this is the host's default device.
 */
isDefault: boolean, };
