// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Supervised long-lived tasks that died and were restarted (E2.2).
 */
export type TaskRestartSummary = { count: number, newest: string | null, 
/**
 * Distinct task names, so the report names the SUBSYSTEM that is unstable
 * (the scheduler missing recordings reads very differently from the trash
 * sweep failing).
 */
tasks: Array<string>, };
