// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConsentStatus } from "./ConsentStatus";

/**
 * The full consent picture, as the settings UI and the onboarding step need it.
 *
 * `status` + `version` are the facts; `needs_prompt` and `active` are the two
 * derived questions callers actually ask, computed here so no caller has to
 * re-implement the "a stale grant is not a grant" rule and get it subtly wrong.
 */
export type TelemetryConsent = { status: ConsentStatus, 
/**
 * The scope version the recorded answer was given for. 0 when never asked.
 */
version: number, 
/**
 * Unix ms (UTC) the answer was recorded, when there is one.
 */
decidedAt: number | null, 
/**
 * [`CONSENT_VERSION`] — what an answer given NOW would be recorded as.
 */
currentVersion: number, 
/**
 * Whether the UI should ask. True when never asked, and true again when the
 * scope has widened since the recorded answer — for a `Denied` user too,
 * because "no" was an answer to a different question.
 */
needsPrompt: boolean, 
/**
 * Whether telemetry may be collected and sent RIGHT NOW. The only flag the
 * backend consults; false in every state except a current-version grant.
 */
active: boolean, };
