// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CorrectionReport } from "./CorrectionReport";
import type { CounterReport } from "./CounterReport";
import type { CrashReport } from "./CrashReport";
import type { FindingReport } from "./FindingReport";
import type { QualityReport } from "./QualityReport";
import type { TelemetryArch } from "./TelemetryArch";
import type { TelemetryOs } from "./TelemetryOs";
import type { WakeFailureReport } from "./WakeFailureReport";
import type { WireSettings } from "./WireSettings";

/**
 * The complete telemetry payload — the ONLY thing that ever leaves the machine.
 *
 * See the module docs for the three-class field discipline, the two judgement
 * calls (no backtraces, reason codes not sentences), and the controller /
 * retention / anonymity terms this contract is one half of.
 */
export type TelemetryPayload = { 
/**
 * [`TELEMETRY_SCHEMA`] at build time.
 */
schema: number, 
/**
 * The consent version this payload was collected under. Lets the endpoint
 * prove, per row, which scope the user actually agreed to.
 */
consentVersion: number, 
/**
 * The random, machine-local install id. Never derived from anything.
 */
installId: string, 
/**
 * Unix ms (UTC) the payload was built.
 */
builtAt: number, appVersion: string, os: TelemetryOs, arch: TelemetryArch, 
/**
 * UI language, primary subtag only. `None` = following the OS.
 */
language: string | null, settings: WireSettings, counters: Array<CounterReport>, crashes: Array<CrashReport>, quality: Array<QualityReport>, findings: Array<FindingReport>, wakeFailures: Array<WakeFailureReport>, 
/**
 * Editor corrections, as coarse bands and counts — see
 * [`corrections`] for the boundaries and the argument for them.
 *
 * Collected under consent v2 and no earlier. The endpoint accepts this
 * field as OPTIONAL and always will: an install still running a build from
 * before it existed sends a payload without it, and a 400 there would be
 * dropped without retry and never surface anywhere. See
 * `sunday-telemetry/src/schema.ts` `OPTIONAL_PAYLOAD_KEYS`, which states
 * the same rule from the receiving side and the deploy order it implies.
 */
corrections: Array<CorrectionReport>, };
