// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The CPU architecture, as a CLOSED set.
 */
export type TelemetryArch = "x86_64" | "aarch64" | "other";
