// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ImageFormat } from "./ImageFormat";

/**
 * The measured facts about a stored cover, feeding the panel's warnings
 * (< 1400 px, non-square, > 5 MB).
 */
export type ThumbnailInfo = { width: number, height: number, byteSize: bigint, format: ImageFormat, };
