// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Whether a resolved cover is this episode's own or the shared default. Absent
 * from `thumbnail_get_default_info` (there is nothing to distinguish).
 */
export type ThumbnailKind = "episode" | "default";
