// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThumbnailInfo } from "./ThumbnailInfo";
import type { ThumbnailKind } from "./ThumbnailKind";

/**
 * A stored cover: where it is, what it is, and something an `<img>` can show.
 *
 * `data_url` is a real base64 data URL rather than an `asset://` path on
 * purpose. The asset protocol is scoped to the standard user folders, so a
 * recording (and its cover) on an external archive volume would resolve to a
 * URL the webview silently refuses to load — a blank preview with no error,
 * which is precisely the failure mode this whole round exists to stop. The
 * [`MAX_BYTES`] cap bounds what that costs.
 */
export type ThumbnailView = { path: string, info: ThumbnailInfo, dataUrl: string, 
/**
 * Which scope answered. `None` on the default-info lookup — omitted from
 * the JSON entirely, and `#[ts(optional)]` so the generated binding says
 * `kind?:` rather than `kind: … | null`. The panel branches on
 * `res.kind === 'episode'`, so a spurious `null` would type-check while
 * describing a payload that never arrives.
 */
kind?: ThumbnailKind, };
