// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One file inside the trash: where it is now, and where it came from.
 */
export type TrashItem = { 
/**
 * Absolute path the file had before it was trashed.
 */
originalPath: string, 
/**
 * Absolute path inside the trash directory.
 */
trashedPath: string, };
