// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TrashItem } from "./TrashItem";

/**
 * One trashed recording — the media file plus the companions that moved with
 * it. The unit the Papirkurv view lists, restores and purges.
 */
export type TrashEntry = { 
/**
 * Stable id (UUID v7 — time-ordered, so the manifest reads chronologically).
 */
id: string, 
/**
 * The recording's own path before deletion.
 */
originalPath: string, 
/**
 * The recording's path inside the trash.
 */
trashedPath: string, 
/**
 * Filename shown in the list.
 */
name: string, 
/**
 * Epoch ms. `f64` to match the `REAL` timestamps everywhere else.
 */
deletedAt: number, 
/**
 * Sidecars that moved with the recording. Attached to the FIRST file of a
 * group that shares a stem (an `.mp4` and its separate-audio `.wav`), so
 * one set of sidecars is never claimed by two entries.
 */
related: Array<TrashItem>, 
/**
 * Size of the media file in bytes, when it could be read.
 */
byteSize: number | null, };
