// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How far the operator moved each boundary of the proposed sermon trim, in
 * signed seconds. See the module docs for the sign convention.
 *
 * Serialised camelCase to match every other record the app persists. It IS a
 * stored shape — [`crate::feedback::TrimAdjustment`] embeds it whole rather
 * than copying the two numbers out, so the sign convention above is stated in
 * exactly one place and cannot be inverted by a second, well-meaning copy.
 */
export type TrimDeltas = { 
/**
 * Seconds the settled start sits AFTER the proposed start (negative = before).
 */
startDeltaSec: number, 
/**
 * Seconds the settled end sits AFTER the proposed end (negative = before).
 */
endDeltaSec: number, };
