// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which way an automatic trim boundary tends to be wrong, if any way is
 * clear yet. Applies identically to the start and the end boundary — see
 * [`crate::trim_feedback`]'s sign-convention table: a positive delta always
 * means the operator pushed that boundary LATER, which always means the
 * proposal sat too early, whichever boundary it is.
 */
export type TrimTendency = "unclear" | "too_early" | "too_late";
