// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TrimDeltas } from "./TrimDeltas";

/**
 * One trim adjustment: how far the operator moved the sermon span the analysis
 * proposed, and which build proposed it.
 *
 * The deltas themselves — and the sign convention that makes them readable —
 * belong to [`crate::trim_feedback`]; this record is that value plus the one
 * thing needed to attribute it. It inherits [`SermonPickCorrection`]'s rule
 * whole: two signed durations and a version string, no time of day, no name,
 * no path.
 */
export type TrimAdjustment = { 
/**
 * How far each boundary moved. Carried as the whole
 * [`TrimDeltas`] rather than copied into two `f64`s here, so the sign
 * convention cannot be re-stated (and inverted) in a second place.
 */
deltas: TrimDeltas, 
/**
 * The app version whose detector proposed the trim being corrected.
 */
appVersion: string, };
