// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which release feed this install follows (E7). Serialised lowercase
 * (`"stable" | "beta"`) — the tag IS the path segment the update Worker serves
 * (`/v1/update/{channel}`, see [`crate::update::channel_feed_url`]), so a
 * renamed variant is a renamed live URL.
 */
export type UpdateChannel = "stable" | "beta";
