// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WakeIdleReason } from "./WakeIdleReason";

/**
 * The outcome of an OS wake-scheduling attempt. Mirrors the Electron `WakeResult`.
 */
export type WakeResult = { ok: boolean, count: number | null, 
/**
 * ISO-like local string of the first/next scheduled wake, or `None`.
 */
nextWake: string | null, 
/**
 * Why it failed: `disabled | cancelled | permission | unsupported | error`.
 */
reason: string | null, message: string | null, 
/**
 * Why a SUCCESSFUL reschedule armed nothing (`ok: true, count: 0`).
 *
 * The engine never sets this — it does not know about the level-1 switch,
 * only about the points it was handed. `commands::wake::wake_reschedule`
 * fills it in, because "nothing to arm" and "why nothing to arm" are the
 * difference between a button that looks broken and one that explains
 * itself. `#[serde(default)]` so an older stored/queued payload still
 * deserialises.
 */
idleReason: WakeIdleReason | null, };
