// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WakeFailureKind } from "./WakeFailureKind";

/**
 * One wake-failure outcome, projected onto the wire.
 *
 * [`WakeFailureEntry::label`] (the slot name — user-authored free text, e.g.
 * "Gudstjeneste Nordstrand") and `scheduled_at` (a local ISO string carrying the
 * congregation's service time) are both absent.
 */
export type WakeFailureReport = { kind: WakeFailureKind, 
/**
 * Unix ms (UTC) the outcome was recorded.
 */
at: number, 
/**
 * The fixed-vocabulary reason token, sanitised.
 */
reason: string | null, 
/**
 * Observed-vs-expected delta for a test wake.
 */
deltaSec: number | null, };
