// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Something the volunteer can DO about it, as a STABLE CODE. Same contract
 * and same reason as [`WakeIssue`] — see its docs.
 */
export type WakeRecommendation = "macKeepAsleep" | "macDisableStandby" | "macStayPluggedIn" | "winKeepAppRunning" | "winSleepNotShutdown" | "winStayPluggedIn" | "winCheckBios" | "useMacOrWindows";
