// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WakeIssue } from "./WakeIssue";
import type { WakePlatform } from "./WakePlatform";
import type { WakeRecommendation } from "./WakeRecommendation";

/**
 * Honest, OS-grounded statement of what wake can and can't do on this host.
 * Mirrors the Electron `WakeCapabilities`. The `knownIssues`/`recommendations`
 * are STABLE CODES ([`WakeIssue`]/[`WakeRecommendation`]) — the app renders
 * them in the volunteer's own language; see those types.
 */
export type WakeCapabilities = { platform: WakePlatform, 
/**
 * Wake from S3 sleep — usually true on supported platforms.
 */
canWakeFromSleep: boolean, 
/**
 * Wake from S5 (off) — false on Apple Silicon, BIOS-dependent on Windows.
 */
canWakeFromOff: boolean, 
/**
 * Scheduling wakes typically needs an admin/UAC prompt.
 */
needsAdmin: boolean, knownIssues: Array<WakeIssue>, recommendations: Array<WakeRecommendation>, };
