// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Why a *successful* wake reschedule armed nothing at all.
 *
 * `ok: true, count: 0` is the same answer for "the schedule is empty", "the
 * weekly plan is switched off" and "everything upcoming is already past the
 * lead" — and a volunteer who just pressed «Registrer vekkinger» deserves to
 * know which. Carried alongside the count so the UI can say it; `None`
 * whenever something was actually armed.
 */
export type WakeIdleReason = "autoRecordOff" | "nothingUpcoming";
