// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How loud a [`BackendWarning`] is. Serialised lowercase to match the
 * renderer's `'warn' | 'error'` union.
 */
export type WarnSeverity = "warn" | "error";
