// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChannelMode } from "./ChannelMode";
import type { FileFormat } from "./FileFormat";
import type { FilenamePattern } from "./FilenamePattern";
import type { SampleRate } from "./SampleRate";

/**
 * The wire-safe projection of the user's settings.
 *
 * [`crate::diagnostics::SettingsSummary`] is NOT reusable here: it carries
 * `device_name` and `save_folder` because a LOCAL report a person reads needs
 * them. This is a strictly narrower type for the strictly stricter context, and
 * the exclusions are the point:
 *
 *   - `deviceName` / `videoDeviceName` — a device name is chosen by the user
 *     and routinely contains a person's or a room's name ("Kari sin mikrofon").
 *   - `saveFolder` / `editorIntroPath` / `editorOutroPath` — filesystem paths.
 *   - `churchName` / `responsiblePerson` — the two fields that would deanonymise
 *     an install outright.
 *   - `emailAddress` / `emailSmtp*` / `webhookUrl` — addresses and endpoints.
 *   - `slots` / `specialRecordings` — user-authored labels and a congregation's
 *     weekly rhythm. Only their COUNTS travel.
 *
 * What IS here is configuration shape: the choices that explain a quality
 * record. `filenamePattern` is included because it is a four-variant enum, not
 * free text — the `Church` variant says "this install names files after its
 * congregation", never what that congregation is called.
 */
export type WireSettings = { channels: ChannelMode, 
/**
 * The sample-rate MODE that actually drives capture.
 */
sampleRateMode: SampleRate, 
/**
 * The resolved forced rate in Hz, or `None` for native capture.
 */
sampleRate: number | null, format: FileFormat, bitrateKbps: number, filenamePattern: FilenamePattern, inputVolume: number, videoEnabled: boolean, stopOnSilence: boolean, silenceThreshold: number, splitMinutes: number, autoDeleteDays: number, trimSilence: boolean, 
/**
 * Whether a pre-roll buffer is armed at all (not how long it is).
 */
prerollEnabled: boolean, showLiveLevels: boolean, 
/**
 * The escape hatch back to ffmpeg audio capture. Whether anyone still needs
 * it decides when the legacy path can be deleted.
 */
classicFfmpegAudio: boolean, 
/**
 * The Windows DirectShow escape hatch, same question.
 */
classicDirectshow: boolean, 
/**
 * Automatic updates. SundayRec has no update CHANNEL concept (one feed for
 * everyone), so this flag is the whole of it.
 */
autoUpdate: boolean, launchAtLogin: boolean, wakeFromSleep: boolean, 
/**
 * How many weekly slots are configured — not what they are called.
 */
slotCount: number, 
/**
 * How many one-off special recordings are configured.
 */
specialCount: number, };
