// E1.7 — tripwires for the security-relevant lists this repo keeps in sync BY
// HAND, with only a comment asking future readers to keep them aligned. Each
// test here fails CI (instead of the control silently drifting) the moment
// one half of a pair changes without the other.
//
// (The third pair — SENSITIVE_HOME_SUBPATHS ↔ tauri.conf.json's asset-scope
// deny list — is covered as a Rust test in
// src-tauri/src/commands/path_guard.rs, next to the constant it guards.)
import { readFileSync } from 'node:fs'
import path from 'node:path'
import { describe, expect, it } from 'vitest'

const repoRoot = path.resolve(__dirname, '..')

// ── CSP: tauri.conf.json vs the <meta> tag in the source index.html ────────
//
// dist/index.html is Vite's BUILD OUTPUT (gitignored, regenerated by `npm run
// build`), not a second source of truth — it is not checked here, and nothing
// else in the repo drift-checks it either.

describe('CSP duplication (tauri.conf.json vs legacy/renderer/index.html)', () => {
  function normalizeCsp(csp: string): string {
    return csp.trim().replace(/\s+/g, ' ')
  }

  it('the <meta> CSP in index.html matches app.security.csp in tauri.conf.json', () => {
    const confPath = path.join(repoRoot, 'src-tauri', 'tauri.conf.json')
    const conf = JSON.parse(readFileSync(confPath, 'utf8')) as {
      app?: { security?: { csp?: string } }
    }
    const confCsp = conf.app?.security?.csp
    expect(confCsp, `app.security.csp missing from ${confPath}`).toBeTypeOf('string')

    const htmlPath = path.join(repoRoot, 'legacy', 'renderer', 'index.html')
    const html = readFileSync(htmlPath, 'utf8')
    const match = html.match(
      /<meta\s+http-equiv="Content-Security-Policy"\s+content="([^"]+)"/,
    )
    expect(match, `no <meta http-equiv="Content-Security-Policy"> tag found in ${htmlPath}`).not.toBeNull()
    const htmlCsp = match![1]

    expect(
      normalizeCsp(htmlCsp),
      `legacy/renderer/index.html's CSP <meta> tag has drifted from tauri.conf.json's ` +
        `app.security.csp — update legacy/renderer/index.html to match (or vice versa) ` +
        `so the two stay identical`,
    ).toBe(normalizeCsp(confCsp as string))
  })
})

// ── windows-check feature list (ci.yml) vs the release.yml Windows matrix ──
//
// The known, intentional difference is `asio`: it needs the Steinberg ASIO
// SDK, which ci.yml's windows-check job deliberately skips (see its comment),
// so ci.yml's list must equal release.yml's Windows list minus `asio`.

function extractFeatureList(text: string, pattern: RegExp, describeWhere: string): string[] {
  const match = text.match(pattern)
  expect(match, `could not find ${describeWhere} — the workflow's shape has changed; update the regex in legacy/security-sync.test.ts`).not.toBeNull()
  return match![1].split(',')
}

describe('windows-check feature list (ci.yml) vs release.yml Windows matrix', () => {
  it('ci.yml windows-check equals release.yml Windows features minus asio', () => {
    const ciPath = path.join(repoRoot, '.github', 'workflows', 'ci.yml')
    const ciText = readFileSync(ciPath, 'utf8')
    const ciFeatures = extractFeatureList(
      ciText,
      /cargo check --workspace --no-default-features --features ([a-zA-Z0-9_,]+)/,
      `the windows-check "cargo check (Windows release feature combo, minus asio)" step in ${ciPath}`,
    )

    const releasePath = path.join(repoRoot, '.github', 'workflows', 'release.yml')
    const releaseText = readFileSync(releasePath, 'utf8')
    const releaseFeatures = extractFeatureList(
      releaseText,
      /- platform: windows-latest\s*\n\s*args: "-- --no-default-features --features ([a-zA-Z0-9_,]+)"/,
      `the windows-latest matrix entry's args in ${releasePath}`,
    )

    const expected = releaseFeatures.filter(f => f !== 'asio')
    expect(
      ciFeatures,
      `.github/workflows/ci.yml's windows-check feature list has drifted from ` +
        `.github/workflows/release.yml's Windows matrix features (minus asio, which ` +
        `ci.yml intentionally skips — it needs the Steinberg SDK). Update whichever ` +
        `file didn't get the feature change.`,
    ).toEqual(expected)
  })
})
