// E1.7 — tripwires for the security-relevant lists this repo keeps in sync BY
// HAND, with only a comment asking future readers to keep them aligned. Each
// test here fails CI (instead of the control silently drifting) the moment
// one half of a pair changes without the other.
//
// (The third pair — SENSITIVE_HOME_SUBPATHS ↔ tauri.conf.json's asset-scope
// deny list — is covered as a Rust test in
// src-tauri/src/commands/path_guard.rs, next to the constant it guards.)
import { readFileSync } from 'node:fs'
import path from 'node:path'
import { describe, expect, it } from 'vitest'

const repoRoot = path.resolve(__dirname, '..')

// ── CSP: tauri.conf.json vs the <meta> tag in the source index.html ────────
//
// dist/index.html is Vite's BUILD OUTPUT (gitignored, regenerated by `npm run
// build`), not a second source of truth — it is not checked here, and nothing
// else in the repo drift-checks it either.

// BOTH shells carry the tag. `app/index.html` is «Frivilligen først»'s Preact
// shell; it is the whole point of the S0 spike that it runs under the SAME
// policy the shipped WKWebView enforces, and the only way that claim stays true
// is if a drift in either file fails here.

describe('CSP duplication (tauri.conf.json vs each shell\'s index.html)', () => {
  function normalizeCsp(csp: string): string {
    return csp.trim().replace(/\s+/g, ' ')
  }

  function confCsp(): string {
    const confPath = path.join(repoRoot, 'src-tauri', 'tauri.conf.json')
    const conf = JSON.parse(readFileSync(confPath, 'utf8')) as {
      app?: { security?: { csp?: string } }
    }
    const csp = conf.app?.security?.csp
    expect(csp, `app.security.csp missing from ${confPath}`).toBeTypeOf('string')
    return csp as string
  }

  /** Every index.html that declares the policy for itself. Prettier formats
   *  `app/` (legacy is ignored), so the attribute may sit on its own line —
   *  hence `[\s\S]` in the tag match and the whitespace normalisation below. */
  const SHELLS: Array<[string, string[]]> = [
    ['legacy renderer', ['legacy', 'renderer', 'index.html']],
    ['app shell (Preact)', ['app', 'index.html']],
  ]

  for (const [name, segments] of SHELLS) {
    const relPath = segments.join('/')
    it(`the <meta> CSP in ${relPath} matches app.security.csp in tauri.conf.json`, () => {
      const htmlPath = path.join(repoRoot, ...segments)
      const html = readFileSync(htmlPath, 'utf8')
      const match = html.match(
        /<meta[\s\S]*?http-equiv="Content-Security-Policy"[\s\S]*?content="([^"]+)"/,
      )
      expect(match, `no <meta http-equiv="Content-Security-Policy"> tag found in ${htmlPath}`).not.toBeNull()

      expect(
        normalizeCsp(match![1]),
        `${relPath}'s CSP <meta> tag (the ${name}) has drifted from ` +
          `tauri.conf.json's app.security.csp — update ${relPath} to match (or ` +
          `vice versa) so the two stay identical`,
      ).toBe(normalizeCsp(confCsp()))
    })
  }

  it('covers every shell that exists — a new index.html must be added here', () => {
    // The failure this catches is a third shell (or a rename) landing with no
    // policy check at all, which looks exactly like green.
    const covered = SHELLS.map(([, s]) => s.join('/')).sort()
    expect(covered).toEqual(['app/index.html', 'legacy/renderer/index.html'])
  })
})

// ── windows-check feature list (ci.yml) vs the release.yml Windows matrix ──
//
// The known, intentional difference is `asio`: it needs the Steinberg ASIO
// SDK, which ci.yml's windows-check job deliberately skips (see its comment),
// so ci.yml's list must equal release.yml's Windows list minus `asio`.

function extractFeatureList(text: string, pattern: RegExp, describeWhere: string): string[] {
  const match = text.match(pattern)
  expect(match, `could not find ${describeWhere} — the workflow's shape has changed; update the regex in legacy/security-sync.test.ts`).not.toBeNull()
  return match![1].split(',')
}

describe('windows-check feature list (ci.yml) vs release.yml Windows matrix', () => {
  it('ci.yml windows-check equals release.yml Windows features minus asio', () => {
    const ciPath = path.join(repoRoot, '.github', 'workflows', 'ci.yml')
    const ciText = readFileSync(ciPath, 'utf8')
    const ciFeatures = extractFeatureList(
      ciText,
      /cargo check --workspace --no-default-features --features ([a-zA-Z0-9_,]+)/,
      `the windows-check "cargo check (Windows release feature combo, minus asio)" step in ${ciPath}`,
    )

    const releasePath = path.join(repoRoot, '.github', 'workflows', 'release.yml')
    const releaseText = readFileSync(releasePath, 'utf8')
    const releaseFeatures = extractFeatureList(
      releaseText,
      /- platform: windows-latest\s*\n\s*args: "-- --no-default-features --features ([a-zA-Z0-9_,]+)"/,
      `the windows-latest matrix entry's args in ${releasePath}`,
    )

    const expected = releaseFeatures.filter(f => f !== 'asio')
    expect(
      ciFeatures,
      `.github/workflows/ci.yml's windows-check feature list has drifted from ` +
        `.github/workflows/release.yml's Windows matrix features (minus asio, which ` +
        `ci.yml intentionally skips — it needs the Steinberg SDK). Update whichever ` +
        `file didn't get the feature change.`,
    ).toEqual(expected)
  })
})
